### ISSUE TITLE
sim4life.io - WP10: Payment Gateway

### ISSUE THREAD

**Issue by SCA-ZMT** [ITISFoundation/osparc-issues#1027]
### From an organization's perspective
- [x] we add a new role of Accountant to organizations (multiple Accountants are possible)
  - an Accountant can:
    - create wallets, from now on credit accounts, associated with the organization
    - buy credits for the credit accounts
    - make the credit accounts available to chosen organization members
(increase awareness of which wallet is actually used - by specifying, or asking/clicking)
  
### From a single user's perspective
- [x]  a user's default wallet (on account creation) is associated to their own personal group. This can't be shared, but it can be disabled.
  - [x] few free welcome credits could be loaded in this private wallet.
- [x]  a user / login can have access to additional credit accounts, if shared by the Accountants of organizations they belong to
- [x] the default wallet for billing newly created studies/projects can be changed in the user preferences
- [x] when opening a study/project, a view prompts the user allowing them to:
  - choose a wallet to charge for this specific session.
- [x] in order not to confront users with cost selections too often, a study/project remembers the hw configuration and wallet that was last chosen when opening it, but allows to change them again
- [x] an indicator at the top of the UI shows in real time the credits available on the default wallet, or the wallet chosen for the currently opened project
- [x] clicking on the indicators opens a view containing the following tabs:
  - an overview of the credits on all available credit accounts, 
  - a list of past transaction
  - a dialog to buy more credits for the credit accounts of which the user is Accountant

### One time payment:
- [x] User selects the amount of dollars to be charged in a specific wallet
- [x] Depending on the type of user (commercial, academic or science) the credit price will be different
- [x] Once the payment transaction is completed, the credits are topped up and the invoice can be found in the transactions section

### Auto recharge:
- [x] User can add a payment method (associated to his wallet)
- [x] User defines a lower threshold for the credits. Once it goes below that number, an automatic transaction (with an amount also defined by the user) is started and charged to the payment method.
- [x] For this automatic transaction, the credit card needs to first be stored in Stripe. oSPARC will only keep a reference to that ``Payment method``.

-------------------- 
2nd iteration:
- [x] when opening a study/project, a view prompts the user allowing them to:
  - a default hardware tier is selected, but the user can go into the advanced settings where other options are available (low/mid/high) corresponding to a cost of credits/hour.
- [x] the default hardware tier (s/m/l) per user is exposed in the User Preferences

-----

```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4752
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5116
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5115
```

```[tasklist]
### Schoggilebe
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5227
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5078
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5327
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/pull/621
- [x] Add backup for appmotion database
```

```[tasklist]
### This is Sparta!
- [ ] https://github.com/ITISFoundation/appmotion-exchange/issues/13
```

```[tasklist]
### Kabayashi Maru
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4657
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/5057
```

```[tasklist]
### Microhistory
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4751
- [x] a user's default wallet (on account creation) is associated to their own personal group
- [x] Auto-recharge: backend functionality @pcrespov @matusdrobuliak66
- [x] Auto-recharge: complete frontend @odeimaiz
- [x] App Motion's feedback @odeimaiz @ignapas @jsaq007
```

**Comment by drniiken** [comment]
In the 7th "S4L retreat" (15.08.2023) it was discussed and agreed that the so far provided working prototype in the UI will be adapted (from a design, perception point of view) to the look of the new S4L website (AppMotion):

- all the data (database, names, credits, etc.) stays on our side !
- AppMotion will help us in the design of this page (pages) - smoothly matching with the "new website"
- finally, we might just render a website on top, being called from our platform
- deploy/login will be provided to AppMotion, Slack channel, etc. (ongoing)

@odeimaiz @mguidon @mrnicegyu11

**Comment by odeimaiz** [comment]
Payment gateway:
- URL containing required data
  - user id
  - wallet id
  - amount of credits
  - total price
  - session id
- Endpoint that the 3rd party middleware will call with the transaction data
  - transaction id
  - transaction state
  - session id

-

**Comment by drniiken** [comment]
Additional information:
https://git.speag.com/oSparc/osparc-issues/-/issues/140

**Comment by pcrespov** [comment]
# Update [Microhistory](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20231101_Microhistory.md)

## Done and working (i.e. ready to be manually tested/used)
- full workflow on **on-time-payment** as in the issue description

## should work in 3 weeks
- payment-methods (front-end ready, backend almost ready and payment-gateway still under dev)
    - add/remove 
    - auto-recharge
    - pay w/ payment-method 
- get ownership and deploy payment-gateway in our account
- ensure stripe banking configurations

## should not be available in 3 weeks
- all features should be ready

**Comment by pcrespov** [comment]
## Update 4Peaks

Most of the work here is done (see tasks above). Missing are

- Final details w/ socketio and error handling for one-time payment https://github.com/ITISFoundation/osparc-simcore/pull/5057
- Onboarding of payments-gateway (MAIN BLOCKER)

**Comment by pcrespov** [comment]
# Update [Kobayhashi Maru](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20231130_Kobayashi_Maru.md)

- ✨ Payment system fully functional (from UI to the bank account)
- ⚗️ Testing period: payments system used with real transactions
   - Tested auto-recharge payments
   - Tested one time payments 
   - Tested management of payment methods
   - Failures detected during testing
      - 💥 External gateway was accidentally misconfigured (app-motion)
      - 💥 Rabbit was disconnected for maintenance (AWS)
      - 🐛 Bug in the front-end (new front-end UX iteration is ongoing) 
- 🚀 Taking over the gateway from app-motion to ops stack (more effort than anticipated)  
   - Build a docker image
   - Deployed as gateway stack (still under test)
   
### Ongoing 🚧

- Finalising integration of the gateway as an ops stack
    - Will allow further testing in staging deploys that were not possible 
- Enhancing user notifications and feedback: fast and effectively inform of the
- Increasing monitoring and alarms 
   - Review and extend payments policies in the event of failure 
- UI/UX iteration on the front-end  (@ignapas will explain more)
