### ISSUE TITLE
ZMT-Specific Deployment on AWS

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-issues#1032]
## Description

In the context of User Privacy (#1030), it has been discussed and decided that it is necessary to have a ZMT-specific deployment for both the sim4life.web and the sim4life.light deploy.

To go there, certain (mainly finance related) questions need to be answered first. Then, a final decision will be made.
(@drniiken)

This includes:

- [x] check current/ongoing cost of sim4life.lite, supported by the STRIDES initiative (currently in the range of USD 12-15k)
- [ ] timeline of NIH, STRIDES support in general
- [ ] @drniiken discuss w/ NK, take final decision

```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/356
```
```[tasklist]
### Kobayashi Maru
- [x] Grafana Dashboard sim4life Usage
- [x] Deployment email zmt.swiss - wontfix
- [x] License Server
```

```[tasklist]
### Baklava
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/410
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/315
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/265
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/317
```

**Comment by matusdrobuliak66** [comment]
![Image](https://github.com/ITISFoundation/osparc-issues/assets/60785969/8ff71c8b-d705-406d-bef3-0f53d142c825)

**Comment by mrnicegyu11** [comment]
done, closing.
