### ISSUE TITLE
Privacy: Deletion of Account, Opting-Out

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-issues#1033]
## Description

In the context of User Privacy (#1030), it has been discussed and decided that users can 1. opt out from collecting data and 2. entirely "leave the platform" and have their account (and everything which is related to it) deleted.

Account Deletion involves:

- [x] Give the option to delete everything from oSPARC / sim4life
- [x] Deletion happens within 48 hours of request, with final confirmation via email
- [x] User entry in database, all associated projects, data, and logs
- [ ] Warn about persistence of data in backups for up to N months

In addition, we shall be transparent to the user with respect to data and user privacy in general, and communicate to the user that:

- We encrypt data
- We do not sell or communicate data to third parties
- We store anonymized data necessary to provide you with the service (debug logs, resource usage, …)
- We might store aggregated data for statistics (possibility to opt-out) [we might leave this away]
- Payment info is handled solely by our payment service provider, we do not store any of it (credit card details, etc.)
- Project data is stored on AWS servers in the USA

We might also need a "contact point", e.g.:
_"For any concerns about privacy, you can contact privacy@sim4life.io”_

```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4620
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1037
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4619
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/315
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4087
```

```[tasklist]
### Kobayahsi Maru
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1203
```

**Comment by mrnicegyu11** [comment]
It looks to me that this is done, the "marketing page" aspect of privacy I have transfered to Anastasia for now. Please contact me or re-open if there is more on the team to be done :--) Cheers
