### ISSUE TITLE
Autoscaling based on selected machines

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-issues#1055]
For the s4life release it is desired that:
- a user can select a machine type to run s4life or other dynamic services
- a machine is created based on need in AWS to accommodate the user's choice.
- there is one machine per service (a.k.a. per user_id/project_id/node_id combination)

### principle
- 1 Autoscaling service per EC2 instance type runs
- dv2 started docker service need to add some placement constraint that represents the chosen EC2 instance type (such as large)
- dv2 started docker service need to add some service label that identify these services as of the chosen EC2 instance type (such that the autoscaling can identify these services)
- the autoscaling settings are hard-coded and need to be in sync with the database

### needed changes
- 1 Autoscaling_small, 1 Autoscaling_medium and 1 Autoscaling_large services each with its own set of settings (each respectively checking the specific tier service labels),
- dv2: change on how dynamic services are started
- possible changes to prevent "machine stealing" by adding constraints based on user_id/project_id/node_id by changing both dv2 and autoscaling

### preliminary analysis
- 👍 (only valid for very simple solution): no code change in Autoscaling service?
- 👎 changes are needed in dv-2, also for the same service different constraints are needed
- 👎 furthermore, there might be "machine stealing" between started S4L. 
  - to prevent this, we would need to add some kind of placement constraint that makes use of the user_id/project_id/node_id combination. Also the Autoscaling would have to set these labels on the started node, such that the docker service may start and go to the correct node.
- 👍 set of settings per machine type, might be "simpler"
- 👎 The autoscaling services ENVs must be kept in sync with the DB information about tier <--> EC2 instance type

### principle
- 1 (or scaled) Autoscaling take care of all the S4L cases
- dv2 started docker service need to add labels that identify the EC2 instance type (this would come from the DB tier <--> EC2 instance type)
- Autoscaling needs to read these labels (if available) and create the instances for them if they are on its allowed list
- If we want multiple buffering policies, then a dictionary shall replace the current buffer ENV

### needed changes
- Change how dv2 starts services by getting what EC2 instance type is needed and passing it on the service labels
- Change how Autoscaling finds the required EC2 instance type by reading it from the optional docker service label
- possible changes for buffering
- possible changes to prevent "machine stealing" by adding constraints based on user_id/project_id/node_id by changing both dv2 and autoscaling

### preliminary analysis
-  👍 1 source of truth in the database regarding tier <--> EC2 instance type, easy update through DB
- 👎 changes in both dv2/autoscaling

## decision:
- I would go with proposal 2

Current proposal:

![Image](https://github.com/ITISFoundation/osparc-issues/assets/35365065/41d5da8f-6da4-4d11-83d9-78bfe49310a6)

```[tasklist]
### Tasks
- [x] General: Create new docker label containing the user wanted EC2 instance
- [x] Autoscaling: If available on the service docker labels read the wanted EC2 instances
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1200
- [x] Webserver: provide API entrypoints
- [x] Apiserver: provide API entrypoints
```

```[tasklist]
### I did not have time
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4767
```

**Comment by mguidon** [comment]
**Note:** As per discussion with POs: If this becomes time critical, we can have one instance type for sim4life at the beginning. (i.e. using an autoscaler as in s4l-lite for the right ec2 instance)

**Comment by GitHK** [comment]
@sanderegg can we consider this one as closed?

**Comment by sanderegg** [comment]
completed
