### ISSUE TITLE
Portal Development

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1080]
Description:
A fixed number of story points (10) is reserved to work on Portal tickets as prioritized by the CCB.

Deliverable: 
10 points per Portal SPRINT to contribute to Portal development work

Deadline: 
Continuous task

```[tasklist]
## Milestone Work

```

## Year 7
```[tasklist]
### sprint 39 [backlog](https://www.wrike.com/open.htm?id=1175230855) \[16/08/2024]
- [ ] [Challenges in understanding AWS downloading](https://www.wrike.com/open.htm?id=1410308660) (1 point)
- [ ] [Clarity on Details page Action Area o²S²PARC button](https://www.wrike.com/open.htm?id=1408704840) (1 point)
- [ ] [Improve access to tools and resources](https://www.wrike.com/open.htm?id=1408696792)(1 point)
```

```[tasklist]
### sprint 38 [backlog](https://www.wrike.com/open.htm?id=1175230844) \[05/07/2024]
- [x] [Bug Submission: Viewing the files in the derivative directory of the dataset in the URL](https://www.wrike.com/open.htm?id=1378220390) (1 point)
- [x] [Bug Submission: trying to open the .xlsx files](https://www.wrike.com/open.htm?id=1363901974) (3 point)
```

```[tasklist]
### sprint 37 [backlog](https://www.wrike.com/open.htm?id=1175230787) \[24/05/2024]
- [x] [Include date last updated in Portal Metrics](https://www.wrike.com/open.htm?id=1337519206) (2 points)
- [x] [No H1 heading](https://www.wrike.com/open.htm?id=1266196978) (3 points)
- [x] [Page has default meta title set](https://www.wrike.com/open.htm?id=1266191072) (5 Points)
```

```[tasklist]
### sprint 36 [backlog](https://www.wrike.com/open.htm?id=1175230735) \[12/04/2024]
- [x] [Bug Submission: Using the sort function in the upper right corner](https://www.wrike.com/open.htm?id=1316499371) (3 Points)
- [x] [No sitemap.xml](https://www.wrike.com/open.htm?id=1266187438) (3 Points)
```

```[tasklist]
### sprint 35 [backlog](https://www.wrike.com/open.htm?id=1175230716) \[01/03/2024]
- [x] [Update re3Data on Portal](https://www.wrike.com/open.htm?id=1267057344) (3 Points)
- [x] [The "Navigating a SPARC dataset" link goes to the wrong page](https://www.wrike.com/open.htm?id=1265611047) (1 Point)
- [x] [Bug Submission: Change the social media description metadata tag](https://www.wrike.com/open.htm?id=1241225415) (2 Points)
```

```[tasklist]
### sprint 34 [backlog](https://www.wrike.com/open.htm?id=1175230686) \[19/01/2024]
- [x] [Vue Migration: Contact Us](https://www.wrike.com/open.htm?id=1266729874) ( 6 Points)
```

```[tasklist]
### sprint 33 [backlog](https://www.wrike.com/open.htm?id=1175230562) \[08/12/2023]
- [x] [QC: Bug Submission: Clicking on contributor should return dataset(s)](https://www.wrike.com/open.htm?id=1215925574) ( 1 Point)
- [x] [Vue Migration: About Page](https://www.wrike.com/open.htm?id=1254707567) (8 Point)
```

```[tasklist]
### sprint 32 [backlog](https://www.wrike.com/open.htm?id=1175229902) \[27/10/2023]
- [x] [Indicate better on sparc.science that SPARC accepts external datasets](https://www.wrike.com/open.htm?id=1194150996) (5 Points)
- [x] [Bug Submission: Address highlighting functionality impacting links (Tool and Resources > oSPARC services)](https://www.wrike.com/open.htm?id=1214691760) (3 Points)
```

**Comment by mguidon** [comment]
Closed in favor of https://github.com/ITISFoundation/osparc-issues/issues/1639
