### ISSUE TITLE
May o²S²PARC Tutorial 3

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1087]
Description:
Tutorial on SIM-Core functionality will be created and published on the SPARC Portal.

Deliverable: 
A tutorial 3 (out of 3)

Deadline: 
Q3

[wrike Y7–(Task) 1d.2.3: o²S²PARC Tutorial 3](https://www.wrike.com/open.htm?id=1157381924)
```[tasklist]
### Tasks
- [x] Create tutorial draft
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1462
- [x] Send the draft to SPARC documentaton experts to review (done in wrike ticket linked above)
```

**Comment by elisabettai** [comment]
The tutorial has been finalized, reviewed and published here: https://docs.sparc.science/docs/tutorial-introduction-to-cad-modeling-on-o2s2parc
