### ISSUE TITLE
TIP v3.0

### ISSUE THREAD

**Issue by Konohana0608** [ITISFoundation/osparc-issues#1155]
As a user/researcher, I would like to do TIP modeling and optimization on an individual level, because every subject's anatomy is different, and personalization to account for that is needed.

- [x] personalization
- [x] customized field libraries (possibly workaround needed)
- [x] improved atlas registration
- [x] **Maroff solver** Postponed
- [x] lossless compression (team)? --> later versions
- [x] Implement behavioral science ideas such as Halo Effect, Integrity by association (put logos of partner universities using TIP), Labor Illusion to give more percieved value (show the variations that are evaluated instead of simple loading bar) --> later versions

```[tasklist]
### Task Content Developers for TIP v3
- [ ] require a shorter to run model for ti-simu (for testing) @Konohana0608
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1155
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1494
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1573
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1577
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1572
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1576
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1570
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1501
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1492
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1510
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1574
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1575
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1571
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1569
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1488
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1489
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1490
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1491
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1493
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1495
```

For the osparc-devteam's tasks, see https://github.com/ITISFoundation/osparc-issues/issues/1309

**Comment by calys** [comment]
@Konohana0608 I suppose I can close this issue... Feel free to reopen if you wish :)
