### ISSUE TITLE
postpro workbench; S-D15, Y3M6

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#12]
advanced postprocessing service to create analysis pipelines with filters (masking, combining, normalization...) and viewers (very large effort, but results in a Sim4Life-like workbench for complex data analyses) 
- [ ] an interactive service exists in o2S2PARC that allows to attach filters and viewers to data to do complex postprocessing and easily create advanced, compound 3D visualizations (similar to the Sim4Life postprocessing tab)

-------
MVP:
- [x] an iframe that provides three elements: 1) graph(/tree) that represents the analysis pipelines, with the ability of adding additional nodes, 2) properties for the currently selected node, 3) a 3D view
- [x] it shall initially be able to handle data in formats from supermash, no physics
- [x] covisualization of CAD

usecase: 
LF results can be loaded, crop filter applied, and slice field view attached

later:
- [ ] EM results can be combined with physics specific filters (e.g., current density extraction, averaged SAR)

**Comment by mguidon** [comment]
**Status Update Brown Islands 20.01.2020**

Simphony:

- EmPostPro
- Extractors
- GenericToolkit
- LicenseManager
- ModelAnalysis
- Networking/JosuaControllerInterface
- SimphonyShared
- TestFixture_ExampleSimulator
- TestFixture_Model
- TestFixture_PostPro
- ToolkitPhased_Array
- XMaterials
- XSimulator

**Comment by odeimaiz** [comment]
Goal for Mythos:
- [ ] Modeler as a Service @pcrespov @mguidon 
- @mguidon, please, extend

**Comment by ignapas** [comment]
### Update before NIH review meeting
* Modelling tree, tools and properties are working although we will go back to it to finish some things, specially about the tools.
* Now working on the postpro/analysis to allow for interactive usage.
  * Tools/algorithms, input selection (files, upload, osparc inputs), viewer properties... coming along.

More detailed update tomorrow evening.
