### ISSUE TITLE
Merge @wvangeit's studies API implementations

### ISSUE THREAD

**Issue by bisgaard-itis** [ITISFoundation/osparc-issues#1291]
```[tasklist]
### Tasks
- [x] `list_studies`: `GET /v0/studies`
- [x] `get_study`: `GET /v0/studies/{study_id}`
- [x] `clone_study`: `POST /v0/studies/{study_id}:clone`
- [x] `create_study_job`: `POST /v0/studies/{study_id}/jobs` in studies_api branch
- [x] `DELETE /v0/studies/{study_id}/jobs/{job_id}` @bisgaard-itis in studies_api branch
- [x] `start_study_job`: `POST /v0/studies/{study_id}/jobs/{job_id}:start` @bisgaard-itis in studies_api branch
- [x] `POST /v0/studies/{study_id}/jobs/{job_id}:stop` @bisgaard-itis in studies_api branch
- [x] `inspect_study_job`: `POST /v0/studies/{study_id}/jobs/{job_id}:inspect` in studies_api branch @bisgaard-itis
- [x] `GET /v0/studies/{study_id}/jobs/{job_id}/metadata` @pcrespov
- [x] `PUT /v0/studies/{study_id}/jobs/{job_id}/metadata` @pcrespov
- [x] `list_study_ports`: `GET /v0/studies/{study_id}/ports` @pcrespov
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/5656
```

**Comment by wvangeit** [comment]
The branch with the code that makes the demo I showed work (api-server-wise, apart from extra services): https://github.com/wvangeit/osparc-simcore/tree/studies_api

**Comment by wvangeit** [comment]
Since the implementation is moved, and seems to be working in master, I will close this ticket. Leftover api endpoints to be implemented, but not required for current metamodelling demo: https://github.com/ITISFoundation/osparc-issues/issues/1391

**Comment by pcrespov** [comment]
> Since the implementation is moved, and seems to be working in master, I will close this ticket. Leftover api endpoints to be implemented, but not required for current metamodelling demo: #1391

@wvangeit you missed two entrypoints I was already working on ...

**Comment by wvangeit** [comment]
@pcrespov ah ok, sorry, i had just moved the open endpoints in this original issue to the new issue

**Comment by pcrespov** [comment]
> @pcrespov ah ok, sorry, i had just moved the open endpoints in this original issue to the new issue

all good. let's sync tomorrow.
