### ISSUE TITLE
sim4life.io User Feedback

### ISSUE THREAD

**Issue by SCA-ZMT** [ITISFoundation/osparc-issues#1305]
This issue serves as a **placeholder** for all user feedback related to sim4life.io.
- You can view the complete list of feedback in the [Sim4Life.io User Feedback Backlog](https://z43.fogbugz.com/f/filters/1437/00-Sim4Life-web-Testing-w-Backlog).
- When addressing any issue from this list, you should either:
   - Create a **pull request** (PR) and reference the original issue using a link.
   - Create a **new gh issue** in this repository and link it to the original issue.

--------

```[tasklist]
### MartinKippenberger
- [x] Active New feedback: Streaming Bar > Click > Set + Move it down [IP]
- [x] Poser Tool crashes upon refresh of the frontend [MaG] - not reproducible
- [x] Active  Wireless Capsule Tutorial View Voxels produces a (reproducible) kernel crash [SCA]
- [x] Analysis pipeline - tree items multiselection looks wrong [SCA]
- [x] New feedback: Specifying cache file doesn... [SCA]
- [x] New feedback: Crash When Starting Streaml... [SCA]
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1767
- [ ] Crash in Guided Tutorial [IP/MaG]
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1739
- [ ] Dragging does not autoscroll the tree [IP]
- [ ] https://z43.manuscript.com/f/cases/204623/New-issue-MS-Biot-Savart-to-Python-Fail [SCA]
```

```[tasklist]
### Tasks
- [ ] Keep installed python packages in project [MaG]
- [ ] Changing "Number of GPUs" in the Solver [MaG]
- [ ] Move Tool buttons highlight looks shifted [MaG]
- [ ] IMSAFE on web [MaG]
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1731
```

```[tasklist]
### South Island Iced Teda
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1525
```

```[tasklist]
### Leeroy Jenkins
- [x] Add issues from Uetliberg Retreat user feedback
```

```[tasklist]
### Enchanted Odyssey
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1380
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1381
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1382
```

**Comment by mguidon** [comment]
Closing in favor of moving to Fogbugz
