### ISSUE TITLE
S4L: 2D plots

### ISSUE THREAD

**Issue by SCA-ZMT** [ITISFoundation/osparc-issues#1311]
```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1358
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1359
- [ ] Expose more settings in 2D plots
```
