### ISSUE TITLE
S4L: UI Form Layouts

### ISSUE THREAD

**Issue by SCA-ZMT** [ITISFoundation/osparc-issues#1317]
This case is about extending our current form views to add different capabilities:
- specify a layout for properties that should be displayed e.g. next to each other
- add the possibility of embedding tables into a form view

First task would be to agree between frontend and backend on a common set of layout types and additional views, and how to pass/parse this information.
### Examples

https://docs.google.com/document/d/1l2k8JoxpABUGsmclfjLU-JmmN2WBpUIMuIqWzQ4o9hE/edit?usp=sharing

```[tasklist]
### Leeroy Jenkins
```

```[tasklist]
### Eisbock
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1421
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1422
- [ ] MaG needs to catch up with the backend
```

```[tasklist]
### Tasks
```

**Comment by mguidon** [comment]
closed in favor of https://z43.manuscript.com/f/cases/209026/Framework-UI-Form-Layouts
