### ISSUE TITLE
S4L Application Features

### ISSUE THREAD

**Issue by SCA-ZMT** [ITISFoundation/osparc-issues#1331]
Please see tasklist ... please address only if there's time.

```[tasklist]
### Martin Kippenberger
- [ ] fixes in IMSAFE
- [ ] Match tool (please see also case #1310 )
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1359
- [ ] Expose more settings in 2D plots
```

```[tasklist]
### Eisbock
```

```[tasklist]
### Tim Bombadil
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1424
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1475
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1579
```

```[tasklist]
### South Islands Ice Tea
```
```[tasklist]
### Leeroy Jenkins
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1423
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1318
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1336
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1471
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1311
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5336
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1320
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1480
```

```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1338
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1319
- [ ] S4L: DASY6 Interop
- [ ] S4L: User-Defined Analysis Pipeline
- [ ] S4L: MUSAIK 2.0
- [ ] S4L: Model links
- [ ] S4L: Dispersion Fitting Tool
- [ ] S4L: Precomputed Waveguides Source
- [ ] S4L: MMT
- [ ] S4L: Flow solver
- [ ] S4L: Video recording
- [ ] S4L: Calculator
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1627
```

**Comment by mguidon** [comment]
# Planning fo sprint [Enchanted Odyssey](https://github.com/ITISFoundation/osparc-issues/milestone/55)
