### ISSUE TITLE
OPs Issues

### ISSUE THREAD

**Issue by SCA-ZMT** [ITISFoundation/osparc-issues#1337]
Placeholder for all tasks related to OPs.

```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/751
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/750
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/749
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/748
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/747
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/736
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/716
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/709
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/618
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/574
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/554
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/530
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/523
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/241
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/769
```

**Comment by mrnicegyu11** [comment]
DevOps dont use this EPIC ticket anymore to collect Ops-Issues. For a list of ops-issues see `osparc-ops-environments`

closing as `does not apply anymore`
