### ISSUE TITLE
Map service for metamodelling

### ISSUE THREAD

**Issue by wvangeit** [ITISFoundation/osparc-issues#1363]
```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1373
- [x] Move map service repository to itisfoundation
- [x] Get Github Actions to run for map service
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1387
```

**Comment by pcrespov** [comment]
@wvangeit some tips on how to setup docker (and docker buildx) in gh-actions can be found in
https://github.com/ITISFoundation/osparc-simcore/blob/master/.github/workflows/ci-testing-deploy.yml#L348-L357
