### ISSUE TITLE
Dakota service for metamodelling

### ISSUE THREAD

**Issue by wvangeit** [ITISFoundation/osparc-issues#1366]
```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1374
- [x] Move dakota service repository to itisfoundation
- [x] Get Github Actions to run
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1386
```
