### ISSUE TITLE
App-team admin panel

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-issues#1395]
The PO center will move into an independent service and accessible via an isolated subdomain  (e.g. `admin.foo.com`). The design should acomplish
1. Fast dev iterations ( views from prototype to deploy ). E.g. @elisabettai stats can be easily ported and exposed in as pannel views 
1. Focus on feature-rich vs looks-rich
1. Independent service release (reduce dependencies so it can be released to production any time)

```[tasklist]
### Tasks
- [ ] New service with read access to data-sources (database, grafana panels?)
- [ ] PO-center enhancements: send invitation email by adding `fogbugz` issue
- [ ] PO center reports: users registration status
```

**Comment by pcrespov** [comment]
## ...

- readonly user in all production deploys so app team 
- `usage_metrics` repo

**Comment by odeimaiz** [comment]
Related to https://github.com/ITISFoundation/osparc-issues/issues/1634
