### ISSUE TITLE
Release Notes Improvements

### ISSUE THREAD

**Issue by SCA-ZMT** [ITISFoundation/osparc-issues#1408]
User-friendly release notes instead of flat list of PRs/Issues. 

Ideally, these release notes could double as the base for the sprint review.

And idea would be to separate the technical changelog and a monthly/periodical "What's New" which could be a curated blog post or pop-up or ...

```[tasklist]
### MartinKippenberger
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1722
```

```[tasklist]
### Tasks
- [x] create separate repository for release notes that is public (for now folder in osparc-issues)
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1563
- [x] sync with app team on where to link the product
- [x] Point products in the deployments to the correct release notes (after release to production on 15th Aug)
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1637
```

```[tasklist]
### Eisbock
```

**Comment by SCA-ZMT** [comment]
@eofli Could you please provide a mockup/example?

**Comment by odeimaiz** [comment]
The way Visual Studio does it:

- In the App: every time (once a month) the app is updated, it shows the Release notes in the app
- In the [website/blog](https://code.visualstudio.com/updates/v1_90): They keep the same content well organized per release

**Comment by odeimaiz** [comment]
Our issues: 
- All products are oSPARC based, but some features only apply to specific products
- We might want to somehow merge the platform specific and app specific release notes: oSPARC +TIP, oSPARC +S4L, oSPARC +S4L-lite, osparc

**Comment by pcrespov** [comment]
IMPORTANT: please do not remove references to the PRs (i.e. the numbers/links) that are already in place, i.e. you can add more info but not remove those links since it is a very useful way to connect witht he changes in the code

**Comment by mguidon** [comment]
We need a follow up:
- Is this working for the App team?
- Service Tabs?
