### ISSUE TITLE
Release to production and testing with selected group of users

### ISSUE THREAD

**Issue by SCA-ZMT** [ITISFoundation/osparc-issues#1417]
```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5822
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5812
- [x] https://github.com/ITISFoundation/osparc-issues/issues/1427
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1429
```
