### ISSUE TITLE
define user registration workflow

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-issues#1513]
```[tasklist]
### Tasks
- [x] [ ] Billable product: Users must go through the registration form
- [x] [ ] What do we do with the tip.itis.swiss users that didn't go through the regsitration form? Expose this data and force fill it up?
- [x] go through the payment process and make sure it's TIP related not s4l
- [x] Add by hand current users in users_pre-registartion table with correct country @pcrespov
```

**Comment by pcrespov** [comment]
## Add by hand current users
- Checked all users in tip.swiss have pre-registraton with valid country alpha2
- Tested registration in front-end https://github.com/ITISFoundation/osparc-simcore/pull/5951
-
