### ISSUE TITLE
Selectable Electrode Size in Personalizer

### ISSUE THREAD

**Issue by Konohana0608** [ITISFoundation/osparc-issues#1569]
```[tasklist]
### Tasks
- [x] Range Slider for Electrode radius
- [x] create electrode templates accordingly
- [x] remove possibliy already placed template and electrodes if user changes the radius repeatedly
- [x] update status file to: 10-10 placed = False if radius is changed
- [x] prevent changing of radius once simulations have been started/done in simulator
- [x] add radius information to targets list json to forward to electrode selector
- [x] update electrode selector label accrodingly
```
