### ISSUE TITLE
Update final versions of all texts on TIP after review by Niels/Sabine

### ISSUE THREAD

**Issue by Konohana0608** [ITISFoundation/osparc-issues#1571]
```[tasklist]
### Tasks
- [x] Implement first draft
- [x] Send draft to PO's for review
- [ ] update all texts once final version is decided upon (Landing Page, Guided Tours, Service Instructions, Pop-ups)
```

**Comment by Konohana0608** [comment]
I updated the text on the simulator popup and file picker instructions. Could you please update the texts on the platform @odeimaiz  as we discussed and close the issue once you are done? Thank you so much~~
