### ISSUE TITLE
Finalize all marketing material

### ISSUE THREAD

**Issue by Konohana0608** [ITISFoundation/osparc-issues#1572]
```[tasklist]
### Tasks
- [x] First Draft: Movie Script, Newsitem, Slogan, Social Media and Website
- [x] Wait for review
- [x] Record Movie
- [x] Edit Movie
- [x] Create Visual for Newsitem
- [x] Pass everything to PO's
```
