### ISSUE TITLE
Update TIP Manual

### ISSUE THREAD

**Issue by Konohana0608** [ITISFoundation/osparc-issues#1573]
For the new release of TIP, the whole Manual has to be overhauled. Personalization needs to be explained and most images need updating. Also, since the platform has changed considerably, many parts of the text as it is now need updating.

```[tasklist]
### Tasks
- [x] First Version of the new Manual
- [x] Wait for review
- [x] Update where necessary
```
