### ISSUE TITLE
"Working Group" TIP: lite

### ISSUE THREAD

**Issue by calys** [ITISFoundation/osparc-issues#1590]
There should be a "lite" version of TIP

- Decision from NK (13.08.2024)
- Some features of TIP are excluded in _lite_ version
- Some users will only have access to _lite_ version

```[tasklist]
### Tasks
- [x] Define list of limitations of _lite_ version
- [x] Determine how to handle the two "flavors" of TIP (different deployments? different access rights to different users?...)
- [x] Decide how to "migrate" existing users
- [x] Decide on timeline (before vs after v3)
```

**Comment by calys** [comment]
Meeting: TIP release 02.09.2024

Participants: NK, EN, Melanie, Kevin, Mayuko, Julian, Nik, SyR


Content of TIP lite:
- no personalized TI planning (templates are greyed out)
- only one TI planning template (“classic TI”, the others are greyed out)
- two anatomical models: MIDA anisotropic + Mouse
- all target regions
- no Exposure Analysis tab (tab is ideally greyed out, or simply invisible)
- no Report generation (“Add to Report”, “Export Report” buttons are greyed out)

Implementation of TIP lite:
- only one product and one deployment
- user accounts grant different types of access (full, lite, etc…)
