### ISSUE TITLE
o2S2PARC API, S-D12, Y3M5

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#16]
o2S2PARC API REST API and Python Interface to o2S2PARC
- [x] a REST API for o2S2PARC exists that permits scripted access and use of o2S2PARC
- [x] a corresponding Python client has been implemented

---
From ITISFoundation/osparc-simcore#503

**Background**
Allow oSPARC use through a non-GUI API (scripting, other). This includes creating a REST API as well as a Python client.

**Definition of Done**
Python interface can be used for:
- [x] authentication
- [x] load/save project
- [ ] setup pipeline
- [ ] display/export results

**Comment by pcrespov** [comment]
## Update [Brown Islands sprint](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20200119_Brown_islands.md):
- Implementing two API gateways. One for the web application (osparc.io) and another for public use (i.e. third-parties and/or our python sdk)
![image](https://user-images.githubusercontent.com/32402063/73837938-cfbb6f00-4812-11ea-9531-b6ee7dcab126.png)

**Comment by odeimaiz** [comment]
Goal for Mythos:
- [ ] Allow creating tokes from Preferences window
@odeimaiz 

API allows:
- [ ] Authenticate
- [ ] List studies
@pcrespov @sanderegg

**Comment by pcrespov** [comment]
## Update Mid-sprint Zhong Zi

### Current Status

  - standalone service for public API gateway [ongoing]
    - Minimal API published
    - Auto-documentation with client-sdk examples (see below)
  - python client SDK [ongoing]
    - [prototype](https://github.com/pcrespov/osparc-simcore-python-client) autogenerated from OAS does not offer best solution.
    - building a template generator
    - emphasis in maintainability 

### Next Steps
  - decoupling services from web-server service
  - 

![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/d3ed7b1a-7dfb-4a68-ad9d-4796fbdd3c26)

**Comment by pcrespov** [comment]
## Update Chrigel Maurer

### Current Status
  - front-end UI to create API tokens [completed]
  - standalone service for public API gateway [ongoing]
    - Minimal API published to fulfill user-story [done]
    - Customized doc and linked to examples [done]
    - Authentication (API-key and prototyped OAuth2) [ongoing]
    - Integrate in swarm and connect to reverse proxy [pending]
  - python client SDK [ongoing]
    - [prototype](https://github.com/pcrespov/osparc-simcore-python-client) autogenerated from OAS 
        - Not optimal. Building a template generator??
  - Connection with web-service [ongoing]
    - issues having two auth systems
  - emphasis in maintainability

**Comment by esraneufeld** [comment]
see as well the related comments at the bottom of #68 (running s4l simulations on osparc by button press). this could be a use case for the api
