### ISSUE TITLE
Investigate GLFW as cross-platform alternative to MFC

### ISSUE THREAD

**Issue by SCA-ZMT** [ITISFoundation/osparc-issues#1605]
```[tasklist]
### Tasks
- [x] prepare glfw 3rd party
- [ ] refactor mfc-dependent classes
- [ ] rewrite UI thread with glfw loop
- [ ] rewrite window creation with glfw
```
