### ISSUE TITLE
request functionalities of osparc python api client for ti-simu

### ISSUE THREAD

**Issue by Konohana0608** [ITISFoundation/osparc-issues#1611]
The Simulation_gui will upgrade to python 0.8. It also needs some support to resolve some errors found during developmtent

```[tasklist]
### Tasks
- [x] Review release workflow
- [x] Doc:Missing https://itisfoundation.github.io/osparc-simcore-clients/#/clients/python/artifacts/docs/BasicTutorial_v0.6.0
- [x] Expose: Wallet api
- [x] tests wallet-api and create doc example @bisgaard-itis
- [x] publish pre-release in pypi instead of test.pypi @bisgaard-itis
- [ ] Review testing (ongoing)
- [ ] Expose: pagination in the client -> iter_jobs, iter_files
- [x] Errors handling: Add OEC in 5XX errors message.
- [ ] Debug get jobs. It still responds with 5XX, 404
- [ ] Delete job does delete more jobs than expected
- [ ] Review doc and tutorials
- [ ] Add feedback by MaG's working group to integrate desktop app
- [x] Check with SAN links
- [ ] Review e2e
```

**Comment by pcrespov** [comment]
there is no follow up on this one.
