### ISSUE TITLE
Add Light UI Theme, Improve Font Usage

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-issues#162]
**ToDo:**

- [x] Choose colors to maximize similarity with portal website
- [x] Add button to top bar to switch light & dark theme
- [x] Make user choice persistent
- [x] Decide & define font(s) to be used: Current fonts are too heavy (font weight). Use font which less havy, e.g. the font currently used for “User manual”. Define three font sizes to be used throughout osparc (small,default,large). Limit dashboard to those font sizes. Make sure the font looks good everywhere in light & dark theme. Note: This might be updated later on when the UI is more stable.

**Rationale:**

- A contrasting light UI theme can reveal poor design choices and compels us to look more closely at how we design elements: Fonts, weights, borders etc.. should look good in both themes!
- A light theme will match the portal website better
- A light theme looks better in presentations, especially in well lit conditions
- Adding a light theme sends a strong message that we care about design

**Comment by oetiker** [comment]
note that I already created a light color scheme for the osparc theme ...
