### ISSUE TITLE
Dashboard Cleanup

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-issues#163]
**ToDo:**

- [x] Move main section selectors (buttons) (Dashboard, Services, Data) to top.
- [x] Remove detail view shown when clicking on a study sheet.
- [x] Activate study on single click
- [x] Move section for templates to top, add new study (use “Empty Study” as label) as normal sheet to front. Use “Create New Study” as title. Move section for existing studies to bottom, use “Recent Studies” as title.
- [x] Increase padding to distinguish sheets better and fix this margin between sheets once a visually acceptable value is found (see next item).
- [x] Center studies in window. Show no more than 5 sheets in one row. Do no increase padding between sheets further, rather increase padding on left and right side of window.

**Notes:**

- Ignore filter, search & sorting for now. Will be defined later.
- Show sheets as grid (as it is done now). List view might be added later.
- The “Create New Study” section might be hideable later.

**Rationale:**

- Showing buttons on the left side is confusing because they “invade” the space for and remove focus from the study sheets.
- The dashboard’s functionality should be simple and focused. It should primarily be for selecting and managing studies. Because its main function is to select and load or create a study, this should be as simple as possible, i.e. with one click. Basic operations auch as delete, rename etc… belong there (see next item). All information belonging to a study should be accessible once it was opened.
- The human eye is bad at distinguishing more than 5 items at once. Hence, limit number of items in a row to 5.

![Dashboard01](https://user-images.githubusercontent.com/32800795/75983602-1ae7a100-5ee9-11ea-806b-ac730caf3c90.jpg)
