### ISSUE TITLE
Cleanup of Study Sheets

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-issues#164]
**ToDo:**

- [x] ~~Use border instead of full color fill. Choose & define default border colors (grey) for both light & dark theme.~~
- [x] ~~Choose & define default border thickness, should reflect & match weight of default font. Make sure borders look ok in both themes. Note: You might need to adapt padding between sheets again, experiment until it looks ok.~~
- [x] Make aspect ratio 5:4 (or somewhere thereof) instead of 1:1.
- [x] Move all text to either top or bottom, but not both. Make use of default fonts.
- [x] Remove created by field and name for both user study sheets and template sheets.
- [x] Remove the last change field for the template sheets, leave it for the user study sheets but remove the string “Last change” in front of the actual last change time.
- [x] Add explanation field for template studies with small text below title.
- [x] Adapt insets, currently the text is too close to the border of the sheets. Define default text inset and use from here on.
- [x] Make inset of thumbnail equal to text inset…
- [ ] Use lighter default thumbnail placeholder. The current vial thing is too heavy.
- [x] Add poop-up-button on right side of title which offers basic commands such as Open, Remove, Rename, Clone, …
- [x] ~~Experiment with adding a fill color again to see if this looks better or worse.~~

**Rationale:**

- Experiment with border and fill for the sheets. 
- A 5:4 ratio for the study sheets better distinguishes horizontal vs vertical direction in the grid layout, makes room for the thumbnail and gives it a more natural look.
- Having the text both on top and at the bottom of the sheets visually merges the sheets with one another and makes it harder for the eye to separate them.
- The create by field does not seem to convey any useful information, as the user studies naturally belong to the current user, and for template studies it’s not clear why the user should care who created them.
- The last change time does not need a title: It is clear already what it means.

![StudySheetUser](https://user-images.githubusercontent.com/32800795/75983911-b24cf400-5ee9-11ea-8a12-f5dbbc17a57c.jpg)

![StudySheetTemplate](https://user-images.githubusercontent.com/32800795/75983919-b8db6b80-5ee9-11ea-8886-efdb201d8aa8.jpg)

**Comment by odeimaiz** [comment]
@drniiken The missing items here are present in #169, therefore it can be closed
