### ISSUE TITLE
API: Create Projects with Associated Data (Feb.)

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#1644]
### Description
Extend public API to create projects with associated data in the application workspace (particularly valuable for Studies with a single Service)

### Deliverable
Extended API functionality, along with documentation

**Acceptance criteria**:
API functionality that permits to perform the above listed functions

### Deadline
Y8Q2 (Feb.)

Wrike [link](https://www.wrike.com/open.htm?id=1396983980) (account/access required)

---

### The Awakening
- [ ] Script-Driven-Development: Implement use case using python osparc client to drive development

### Singularity
- [ ] Refactor web-server projects module

### Tasks
- [ ] Implement use case using python `osparc` client to drive development
- [ ] api: create study with one service (limit)
- [ ] api: add file to node's state. Implement as `move` file resource to study
- [ ] Refactor webserver projects: job-to-project table
- [ ] Refactor webserver-api-server comms using rpc
- [ ] api: connect services?

**Comment by bisgaard-itis** [comment]
Here's a summary of a discussion me and @pcrespov had about this issue:
The key issue to determine is how much functionality must be exposed in the api server in order to have a valuable framework while keeping the api as minimal as possible. In a first implementation we have decided to go for an approach where we utilize the concept of templates which we have in the following way:
- Rather than creating a project "piece by piece" via the api-server the user can clone template projects/studies with a desired structure. E.g. a template could be template study with a single service node inside.
- In order to place the associated data into the newly created project we will add the following endpoint to the api-server
```
POST /studies/{study_id}/file/{file_id}:move
```
whose body is
```
{
  relative_destination_dir: string
}
```
(potentially this could be a subresource of the `files` section of the api instead of the `study` section). As is, this endpoint assumes the project only holds a single node and the api-server will be responsible for figuring out what's the id of that node. 

One advantage of using the template approach is that it doesn't open the door for the user to create arbitrary projects. Moreover, with a very general API it will be hard for the user to create a meaningful study/project with e.g. a complicated workbench.

**Comment by pcrespov** [comment]
## Summary for [The Awakening](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20250404_TheAwakening.md) sprint

- The osparc [public-api has been extended](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/bisgaard-itis/osparc-simcore/refs/heads/1870-start-program-section-of-api-server/services/api-server/openapi.json) with a new concept: *programs*
- The public-api offers as a program any dynamic service registered in the osparc catalog    
- Can create an instance of a *program*
	- An instance is denoted as *program’s job*
	- All *program’s jobs* are also displayed the front-end as a Study in the dashboard
- Any program’s job has a*workspace* folder
- The public-api offers the possibility to upload data to the workspace before it starts    
- These functionality has also been exposed in the osparc python-client
- Workflow: python client can create now programs in the platform and set up their workspace


![Image](https://github.com/user-attachments/assets/ba1cdf68-1969-45b3-8c1c-7e2b2764d466)
