### ISSUE TITLE
oSPARC Study Editor Part I

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-issues#168]
**ToDo:**

 - [x] 1. Move the study tree and friends to the left side of the screen.
Rationale: The overwhelming majority of tools shows the major navigation and control elements on the left side. We read from left to right, and that is also how we interpret a user interface. We expect the most important parts on the left, and the detail stuff to the right.
- [ ] 2.     Remove the log and study info frames. Instead, add button at the bottom to bring them up.
Rationale: In a normal workflow (where there are no errors), both frames are irrelevant most of the time. Both are of the kind that the user might want to be able to see, but only rarely. Later, we might think about how to alert the user of errors that were added to the log, but as long as everything is ok, the log is not very helpful.
- [ ] 3.     Add a settings frame next to the service tree. This frame does not need to be populated right now. Optionally, you could experimentally add elements that are common to every service, such as stuff shown in the workbench nodes like progress, control buttons, number of inputs/outputs etc…
Rationale: It seems reasonable to expect that the nodes in the service tree (and/or workbench) have quite a few common settings/parameters/controls. It is quite annoying to use the entire workbench area to show those settings. Thus, we want to explore if we can streamline this into a common settings frame that shows said common service elements in a useful way. And the first step is to see how such a settings frame looks and feels.
- [ ] 4.     Add a Data pane below service tree and settings. This frame should essentially show something akin to the file picker dialog. Optionally: Add means to directly create a file node in the workbench/service tree. Ideally this can be achieved by simply dragging & dropping a file from the Data frame into workbench or service tree, and/or by adding inline buttons in the file tree.
Rationale: At the heart of the oSPARC service is the actual data!!, mainly input data as well as results! As a user, I very much want to be in control of this at any point in time. While this is not necessary for a desktop app because most OSs have very solid file systems, in a web app I need to have means to easily survey and access my data. Also, this will allow us to simplify many workflows considerably.
- [ ] 5.     Move the “Path to currently selected service” thingy into a frame at to the top of the main content area (workbench area). This is essentially what is shown in the top bar (next to “Dashboard”), when you select a service in the workbench.
Rationale: The topmost area should be reserved for the toplevel navigation elements (Dashboard, user settings, etc…). The currently selected element is part of a study and should as such not be located in the toplevel bar.
- [ ] 6.     Add a “Workbench” button next to the path selector. This button allows the user to bring back the workbench at any point in time. I can then, for example, select another node in the workbench.
Rationale: As the workbench is supposed to be the central point of entry for the user, it should be extremely easy and obvious how to access it. Note: As a user I would expect that this button does not change the current selection! I.e. the service tree and the path selector still list the same service as being selected/active. Consequently, also the settings frame does not alter its content. By clicking it again, I get back to whatever was shown before.

**Notes/Observations:**

1. When playing with the collapse/expand buttons in the service tree and friends, I noted that a vertical scrollbar appears/disappears without clear need. I would rather put scroll frames into the service tree frame, settings frame as well as the data frame themselves.
Rationale:  Those essential frames should never disappear from the screen to make their (also essential) functionality accessible at all times. But their content, which could get large, should be scrollable by all means.
2. If I resize the browser, I can “hide” the service tree for example. Those elements should have layout priority, i.e. they should always be visible. Instead, the workbench should be shrinking if the browser frame get’s smaller. Think about what the min/max width of those elements should be.
3. Fonts: As discussed for the dashboard, also here we should strive to use only a few well defined font sizes/weights.

![Screenshot 2020-04-19 at 23 08 17](https://user-images.githubusercontent.com/32800795/79699935-c6c72f00-8292-11ea-821c-8aefac38c575.jpg)

**Comment by drniiken** [comment]
Still to be discussed and refined ... thanks and best, Nik
