### ISSUE TITLE
Dashboard Cleanup, Follow-Up I

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-issues#169]
This is a follow-up case of #163 .

**ToDo:**

- [x] 1. (and 2.) The dashboard button doesn’t help if we are already in the dashboard… 
- [x] 2. The three subsection buttons look out of place. I would actually put them in the top bar, since the “Dashboard” button is useless here. Alternatively, you could stack then vertically on the left side, below the osparc logo. At the least, align the weird underline (cf 3.).
- [x] 3. Alignment: Can you make the major elements align on the leading edge?
- [x] 4. Fonts: As discussed, you should think about defining a couple of standard font types (think about style, weight, etc…) and try to use them throughout the UI.
- [ ] 5. Filtering elements: I would try to put them in the same line as “New studies”, aligned on the trailing edge to the study sheets. Also, duplicate and add the same elements to the “Recent studies” section. And, of course, the filter(s) should then only be applied to the corresponding section. See also 6…
- [x] 6. There are too many “New studies” templates. We probably don’t need to 5 interconnected sleepers twice? I would try to limit that for now. If you manage to do that, then maybe you don’t need filters for that section at all.
- [x] 7. Missing padding: The text box for the titles is not correct, it overlaps with the button (e.g. “ISAN: osparc-opencor…???”).  Think about how to deal with a title that is too long. Truncate it with ellipses? Just cut it? Auto-scroll it? Show a tooltip with the full title when hovering over it? Also, I would align the  baseline of the title with the 
- [x] 8. I would align the title text’s baseline with the button’s bottom border.
- [x] 9. I would rename the title to “New Study”or “Empty Study”, and remove the icon (it’s an empty study after all…)
- [ ] 10. A placeholder icon is ok, since those studies are not empty. But I would go for a less bulky one, as this one is so heavy that they draw all the attention. As an idea: There are a lot of template names that start with “[ISAN]”. Why not reomve “[ISAN]” save some space in the title and put an ISAN icon below?
- [x] 11. The icons/screenshots boxes should be aligned at the bottom and of equal size. Right now, the icons appear to be higher than the jupyter logo, and the Sleepers image is of different size than the OpenCor image. In general all those element boxes (title, detail text & email, icon/image) should be the same for every study sheet.
- [x] 12. Study sheet aspect and padding. I would go for a bit more padding and a shape that is longer vertically than horizontally to make it look more like a sheet of paper. 

![Image 17 04 20 at 09 09](https://user-images.githubusercontent.com/32800795/79696573-b0fb3f00-827d-11ea-9429-2015462f618d.jpg)

**Comment by drniiken** [comment]
We'll still merge the cases/items ... thanks and best, Nik
