### ISSUE TITLE
sim4life web: Maintenance and Bug Fixing

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-issues#1695]
Placeholder for all generic maintenance and bugfixing in the sim4life web application

```[tasklist]
### MartinKippenberger
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1692
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1734
- [x] Fix bug with linked properties
- [x] Huge images sizes!!
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1700
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1733
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1731
```

```[tasklist]
### Tasks
- [ ] Notebook Tutorials
```

```[tasklist]
### Eisbock
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5950
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1696
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1707
```

**Comment by mguidon** [comment]
Closing in favor of gitlab issues from now on
