### ISSUE TITLE
Add Monkey Model

### ISSUE THREAD

**Issue by Konohana0608** [ITISFoundation/osparc-issues#1743]
```[tasklist]
### Tasks
- [x] Compile model correctly in Sim4Life
- [x] Apply electrodes to the model
- [x] Create simulations for each electrode
- [x] Run all simulations
- [x] Evaluate Simulations: resample fields and extract integrated currents
- [x] Upload all necessary files to new image of TI Postpro
- [x] make monkey available only to Fabien's team
```

**Comment by Konohana0608** [comment]
Questions during Discussion:
- Should Other_Connective_Tissue be tagged with Salivary Glands?
- Are electrode locations reasonable? Should we add more?
- What is the radius/surface area of such electrodes? 0.8-1 mm
- Does Priority 1 mean it overwrites any other tissue correct?
- send DTI example to show what we need (done)
