### ISSUE TITLE
Add tags to Resource Tracker (Reporting)

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-issues#1771]
Add the possibility to use tags to help with reporting of project costs. (req. by Jacqueline)
```[tasklist]
### Event Horizon
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6722
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1819
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1808
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1809
```

```[tasklist]
### Tasks
```

**Comment by odeimaiz** [comment]
What happens if later the Project gets untagged? Or tags change?
