### ISSUE TITLE
Solver Plugin

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-issues#1785]
Work with Lucia on generalizing the FEniCS integration to a solver plugin concept.
```[tasklist]
### Tasks
- [ ] review class concept from lucia
- [ ] provide API functionality that is required
- [ ] later: functionality needed for 3rd party users to bring their plugin in
```

**Comment by mguidon** [comment]
Moved.
