### ISSUE TITLE
macro/templates, towards guided mode, S-D10, Y3M4

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#18]
Enable users to encapsulate entire workflows (macro/template) and define user-exposed parameters - step towards guided mode x Specific o2S2PARC Functionality 
- [x] Functionality exists in o2S2PARC that allows to setup a computational pipeline, wrap it as a macro-algorithm, and define the parameters of the underlying building blocks that are exposed to users of the macro- algorithm. 
- [x] these macro-algorithms represent encapsulated workflows that can be shared and used, also by users with limited expertise. 
- [ ] In a subsequent step (Y4), we plan to allow to access workflows as dedicated webpages, while hiding the complexity of oSPARC (no workbench, no pipelines, etc.). In this guided mode, users will see a kind of wizard that steps through a limited number of dialogues or interactions and then produces results. This functionality requires the one developed during Y3 as a technical basis.

**Comment by odeimaiz** [comment]
Goal for Mythos:
- [ ] Exported groups are persistent and available in the catalog
- [ ] Only Group owner can delete it

**Comment by odeimaiz** [comment]
State:
- One can export a group selecting what inputs are exposed and which are their values
- Exported groups are persistent and available in the catalog
- Only Group owner can delete it
