### ISSUE TITLE
simple creation of data-processing modules, S-D7, Y3M2,4,5,2-12

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#21]
service to support the creation of data analysis modules (e.g., out of a matlab/bash/python/R script; through dedicated webGUI) to make them shareable and useable as part of pipelined workflows making this user-friendly is to get SPARC researchers to put their analysis scripts on the platform and share them. It is key to the new focus on broadening the platform from simulations to general computational studies. SIM-CORE will reach out to SPARC teams in advance to identify existing data analysis functionality and requirements, and later to encourage onboarding. published analysis modules shall be visible in the o2S2PARC service catalogue, and shall also be found on a dedicated page on the Portal
- [x] **(a)** the SIM-CORE application and support team has reached out to SPARC teams to identify/ gather feedback about the existing and required data analysis and visualization functionalities (M2)
- [x] **(b)** a webGUI exists that allows a user to easily turn a data analysis script (matlab/bash/python/R) into a pipeline-able service that is accessible and shareable through o2S2PARC (M4)
- [x] **(c)** published analysis modules are visible in the o2S2PARC service catalogue, and can also be found on a dedicated page on the Portal (M5)
- [x] **(d)** the SIM-CORE application and support team reaches out to SPARC teams to encourage and support onboarding of data-analysis functionality (year-long)

**Comment by pcrespov** [comment]
## Update [Brown Islands sprint](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20200119_Brown_islands.md):

-  Running python script to process data
![Peek 2020-02-05 11-54](https://user-images.githubusercontent.com/32402063/73836003-adbfed80-480e-11ea-87a9-c5c653133815.gif)

**Comment by pcrespov** [comment]
This is the workflow envisioned from code/script to service

![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/0efb7f6d-4093-45de-aa9a-9ee2b258ba6a)

This is how we are encapsulating services
![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/bb6534a2-510c-4622-b9d8-bda88449e3c7)

**Comment by KZzizzle** [comment]
related to https://github.com/ITISFoundation/cookiecutter-osparc-service/issues/11#issue-457272658

**Comment by KZzizzle** [comment]
related to Python Script service:
https://github.com/ITISFoundation/osparc-simcore/issues/1175

**Comment by KZzizzle** [comment]
Regarding part **(b)**, mockup of submission website : https://kzzizzle.github.io/inputform/

**Comment by odeimaiz** [comment]
Goal for Mythos:
- [ ] Standalone website for creating computational services (scripts).
- [ ] Extend [react-jsonschema-form](https://github.com/rjsf-team/react-jsonschema-form) for creating metadata
- [ ] Some curator checks validity
- [ ] Generate service with the cookiecutter, push to registry
- [ ] It is available in the Catalog

@KZzizzle @sanderegg @pcrespov

**Comment by sanderegg** [comment]
State:
- Cookiecutter
  - update in progress to simplify its use [see related issue](https://github.com/ITISFoundation/cookiecutter-osparc-service/issues/11)
  - currently in pause to focus on platform stabilisation for portal hard-launch

**Comment by ignapas** [comment]
#### User interface for new services submission
* JSONSchema to web form generation
* Array items
* Required and regex pattern validation of values
#### Current generated form:
![Screenshot from 2020-02-26 13-30-35](https://user-images.githubusercontent.com/4764217/75345471-13971680-589d-11ea-8548-3449aa608155.png)

**Comment by KZzizzle** [comment]
![image](https://user-images.githubusercontent.com/28002886/76007544-8132ea80-5f0e-11ea-9d96-bff5f76f70f7.png)

**Comment by sanderegg** [comment]
### Cookiecutter for osparc-service creation:
- source code located in [cookiecutter-osparc-service](https://github.com/ITISFoundation/cookiecutter-osparc-service)
- allows creation of services (cookies) using different docker image flavors (ubuntu-18.04, docker python official image, python-alpine, centos)
- provides pre-filled CI for Github and Gitlab
- simplified structure and usage
- usage of an integration version for further development on the integration (now io.simcore.integration-version set to 1.0.0)
- follows latest oSparc good practices

**Comment by ignapas** [comment]
### On service service submission UI part
* A new autogenerated form is ready with the following capabilities
  * Using a single schema to generate
  * Allows for enums and properties with MIMEType to be rendered as SelectBoxes and FilePickers respectively.
  * Sends the file and the service information to an already created API endpoint.
### To be completed
* An email is composed and sent to appropriate stakeholder.
* Further develop and automatize the process, giving support for submission status/management by the user and/or curators.

**Comment by KZzizzle** [comment]
TO DO: automation of creation of Matlab and Python services based on the  submission form
