### ISSUE TITLE
access rights, S-D6, Y3M6

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#22]
o2S2PARC: fine grained access rights (viewing, execution, derivation, modification of parameters, modification of pipeline, modification of service content...) per user/organization
- [ ] fine-grained access rights can be assigned to different users or organizations that control what they can do with an o2S2PARC study (see, modify parameters, modify the pipelines ... )

Comment for the Sprint Planning of May 14th:
we rapidly need a concept that extends beyond templates (which must be instantiated - copied - to work with), to include studies (so groups can modify/... an instance) and services.
It was pointed out during the review, that the separation into templates, studies, and services might not be suitable anymore. Early during the Sprint, a working group shall therefore discuss how to proceed. Please, include EN in that WG.

**Comment by odeimaiz** [comment]
Goal for Mythos:
- [ ] Organization management is handled in the backend.
- [ ] I create a template available only to "ITIS_Foundation" organization
- [ ] I create a template available only to a specific user

@sanderegg @odeimaiz

**Comment by odeimaiz** [comment]
Focused on sharing resources in a different way.
Minimal version in the frontend. Backend is missing.
https://github.com/ITISFoundation/osparc-simcore/pull/1310

**Comment by sanderegg** [comment]
Design will be following linux access rights:

- each user will have a group with the same name (e.g. user's primary group)
- a group will have an ID, name, and list of users that are part of that group
- projects already have a project_owner, they will also have access rights where a list of groups with respective read/write/execute rights will be set

foreseen issues:
- when sharing a project with a group, a check on the services should be done in case some services are not accessible to some groups

**Comment by sanderegg** [comment]
## Update on [Zhongzi](https://github.com/ITISFoundation/osparc-simcore/milestone/23)

Backend:
- Database modification + migration scripts to list groups ready
- Database modification + migration scripts for access rights to projects ready
- work in progress: setting up endpoints for frontend to allow to define access rights to project when creating template
- open: check how data is copied when creating template

**Comment by sanderegg** [comment]
## Update on sprint [Chrigel Maurer](https://github.com/ITISFoundation/osparc-issues/milestone/6)

# Current Status
Backend:
- allow creation/modification/removal of groups by a standard user
- allow adding/removing existing users to a group and setting administration rights (read, write, delete) based on user rights on group
- allow setting access rights to n groups on a study instance, thus allowing sharing of studies between users
Frontend:
- management of groups
- management of users in groups
- sharing of studies and setting access rights

# Open issues/ongoing development: 
- testing on access rights checks
- notifications (invitation to access shared study, prevent concurrent access to study)
- invitation to share study through e-mail (non-existing user or out of group)
- return number of users in a group, paging of users
- concurrent access (synchronization) to studies

**Comment by esraneufeld** [comment]
see as well the related comments at the bottom of #68

**Comment by sanderegg** [comment]
## Update on sprint [Huo Guo](https://github.com/ITISFoundation/osparc-issues/milestone/7)

# Completed
## Management of groups:
- user can create groups and add/remove users to it
## Sharing of studies
- user can share a study with another user and define access rights to the study
- locking mechanism prevent 2 users from opening the same study at the same time

# Open issues/ongoing development: 
- issue when 2 users open a study almost at the same time
- notifications (invitation to access shared study, prevent concurrent access to study)
- invitation to share study through e-mail (non-existing user or out of group)
- return number of users in a group, paging of users

**Comment by sanderegg** [comment]
## Update on sprint [Xie Xie](https://github.com/ITISFoundation/osparc-issues/milestone/8)

# Current Status
### Management of groups:
- tester can create groups 
- user can add/remove other users to it if they have group access
### Sharing of studies
- user can share a study with another user and define access rights to the study
- locking mechanism prevent 2 users from opening the same study at the same time

# ongoing development:
### Sharing of services
- services are shared with everyone by default
- catalog micro-service provides more fine-grained access to services based on the user groups/organizations
- developer can restrict access to services or allow access to defined groups by editing the database


# Open issues/ongoing development: 
- issue when 2 users open a study almost at the same time
- frontend cache is not invalidated when a second user changes the study
- access rights for services through catalog micro-service
- notifications (invitation to access shared study, prevent concurrent access to study)
- invitation to share study through e-mail (non-existing user or out of group)
- return number of users in a group, paging of users from backend
