### ISSUE TITLE
support onboarding of SPARC computational models, S-D1, Y3M1-12

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#26]
Collaboration with SPARC teams to support onboarding of their computational models (e.g., Morris, Keast, Horn) and data processing modules
- Continuous support for model onboarding has been provided to the SPARC teams. 
- We are supporting teams that contact us about onboarding their models
- We actively approach selected researchers, when we identify that they have suitable models.

-----
currently pending:
- [x] Kember: Isosplit
- [x] Kember: Multilevel1
- [x] Kember: Multilevel2
- [x] Generic OpenCOR
- [x] Grandi
- [x] Morris: simrun
- [x] Lemaire: PySONIC
- [ ] Julius: pulse_adjoint
- [ ] Mavi's image segmentation: requires GPU
- [x] Morris: simbuild: requires GUI
- [x] Morris: simviewer: requires GUI

**Comment by KZzizzle** [comment]
# Update for Xie Xie Sprint

Kember Multilevel 1 and 2 on staging as a template, awaiting review by Guy Kember

![image](https://user-images.githubusercontent.com/28002886/89017145-22856780-d31a-11ea-98fa-d80fd28466e3.png)

**Comment by drniiken** [comment]
Dear @KZzizzle , could you please resolve this case and take the remaining ones over to Y4.
Thanks and best, Nik

**Comment by esraneufeld** [comment]
hi priority in this sprint: grill pipeline... ( @KZzizzle )

**Comment by elisabettai** [comment]
Closing this onr favor of #694 for Y6.
