### ISSUE TITLE
S-D23.1 Data Analysis and Derived Data: Organization Y4M06

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#329]
Organization of (script-based) services, assure that they are visible and can readily be found **Y4M06**
- [x] filtering & search (faceted & tagging & classifiers)
combination of text search & faceted search (similar to fogbugz search); criteria include:
  - creator/ownership
  - meta data text
  - tags & classifiers
sorting should reflect match, but can later be extended with intelligence to reflect usage frequency, quality rating, user-specific activity...
- [x] curated tagging (incl. review process for classifiers/hierarchical keywords)
- [ ] concept based on federation of external service stores (public SPARC, organization specific ones...)

related to next item (git) and to access rights

This search&discover functionality should be usable as an element in different places:
- to find a service on the workbench (service browser)
- to create a new study following a template from the dashboard (button next to the 'new empty study' button)
- ...
