### ISSUE TITLE
S-D25.4 Simulation framework SCHEDULER Y4M05

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#349]
- [x] Intelligent scheduler and queueing; 
- [ ] including for HPC

keep in mind
- [ ]  running MPI parallelized codes across multiple containers #346 
- [x] backend for guided mode #327 - done
- [ ] scalability #350 

Definition of Done:
- It is possible for a service to provide information about resources that it requires (estimated RAM, need for a certain kind of GPU, number of cores, perhaps even estimates of runtime - think s4l EM simulations). It gets dispatched accordingly.
- Dependencies are automatically converted into optimized execution orders and parallel execution where feasible
- Services that declare (s. above) that they support MPI can be executed across multiple docker instances with a shared MPI framework. For that, they are dispatched to suitably ‘close’ machines
- Progress of queued/completed jobs can be inspected (queue manager) and tasks can be removed from the execution queue, or their relative priority adapted (less urgent).

User story:

Beyond done:
- The necessary HW requirement information is part of a service’s meta-data, but can also be inspected by users (e.g., in the info section of the service)
- Users with the necessary permissions can edit some of these settings (e.g., number of parallel instances in an MPI-parallelized service)

-------------
MVP for closing (25.4 and 25.5)
- [x] finish computational and dynamic sidecars
- [ ] dask gateways (incl. for AWS)
- [x] ability of adding additional HW (incl. AWS; incl. frontend)

**Comment by sanderegg** [comment]
## status as of 03.01.2021
### Done:
- Computational states are now retrieved per node (modified, waiting for dependencies) backend + frontend
### Ongoing:
- Bugfixing on concurrent updates of nodes after running in a pipeline (when several sidecars are used on one pipeline)
- Moving scheduling, currently done by sidecar itself to director-v2 --> simplifying architecture, reducing possible issues to allow for open enhancements/issues
### Open:
- ensure that sidecars do not access DB directly to remove the DB max connection problem
- test using [Airflow](https://airflow.apache.org/)/[Prefect.io](https://www.prefect.io/) for finer grained dispatching of computational pipelines
- create a *Computational Resource Manager* micro-service (CRMs) that would monitor the computational queues (load) to start/stop machines and sidecars to cope with variable computational load.
-

**Comment by sanderegg** [comment]
## Update on sprint [Red Panda](https://github.com/ITISFoundation/osparc-issues/milestone/16)

### Done:
- Bugfixing on concurrent updates of nodes after running in a pipeline (when several sidecars are used on one pipeline) [#2174](https://github.com/ITISFoundation/osparc-simcore/issues/2174) --> will be deployed to production next sprint
- Moving scheduling, currently done by sidecar itself to director-v2 --> simplifying architecture, reducing possible issues to allow for open enhancements/issues [#2164](https://github.com/ITISFoundation/osparc-simcore/issues/2164) --> will be deployed to master next sprint (was waiting for maintenance cases to go in first)
### Ongoing:
- Evaluation of [Apache Airflow](https://airflow.apache.org/) / [Prefect.io](https://www.prefect.io/) as workflow management tools [#1992](https://github.com/ITISFoundation/osparc-simcore/issues/1992)
- Creation of dynamic service sidecar, to allow for improved security, better handling of dynamic services [#1887](https://github.com/ITISFoundation/osparc-simcore/issues/1426#workspaces/osparc---scrum-wall-5c9260f3d76ef51f6b0fe78d/board?repos=118596920,181836792,210862626&search=sidecar)
### Open:
- ensure that sidecars do not access DB directly to remove the DB max connection problem [#2239](https://github.com/ITISFoundation/osparc-simcore/issues/2239)
- create a Computational Resource Manager micro-service (CRMs) that would monitor the computational queues (load) to start/stop machines and sidecars to cope with variable computational load. [#2240](https://github.com/ITISFoundation/osparc-simcore/issues/2240)

**Comment by pcrespov** [comment]
## Update on sprint [Marmoset](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20210705_Marmoset.md)

### Done:

- Adds dask scheduler and sidecar worker in stack (ITISFoundation/osparc-simcore#2366) 


### Ongoing:

- Integration of dask in director

### Open:

- ensure that sidecars do not access DB directly to remove the DB max connection problem [#2239](https://github.com/ITISFoundation/osparc-simcore/issues/2239)
- create a Computational Resource Manager micro-service (CRMs) that would monitor the computational queues (load) to start/stop machines and sidecars to cope with variable computational load. [#2240](https://github.com/ITISFoundation/osparc-simcore/issues/2240)

**Comment by sanderegg** [comment]
## Update on sprint [Chevrotain](https://github.com/ITISFoundation/osparc-issues/milestone/22)

### Done
- Added facilities to create, modify, remove clusters and share them among groups of users [#2517](https://github.com/ITISFoundation/osparc-simcore/issues/2517), [#2502](https://github.com/ITISFoundation/osparc-simcore/issues/2502), [#2499](https://github.com/ITISFoundation/osparc-simcore/issues/2499)
- Dask-sidecar to advertise clusterID if available on start [#2505](https://github.com/ITISFoundation/osparc-simcore/issues/2505)
- Improving resiliency of Dask-based backend [#2514](https://github.com/ITISFoundation/osparc-simcore/issues/2514)
- Allow dask-sidecar to run multiple services in separate threads [#2486](https://github.com/ITISFoundation/osparc-simcore/issues/2486)
- Improvements on node ports package (remove globals) [#2487](https://github.com/ITISFoundation/osparc-simcore/issues/2487)
- Connect director-v2 to dask-based backend [#2418](https://github.com/ITISFoundation/osparc-simcore/issues/2418)
- Bugfixes on dask-based backend [#2512](https://github.com/ITISFoundation/osparc-simcore/issues/2512), [#2508](https://github.com/ITISFoundation/osparc-simcore/issues/2508), [#2503](https://github.com/ITISFoundation/osparc-simcore/issues/2503)
- Tested connection with AWS machines through docker swarm
### Ongoing
- Remove celery sidecars [#2528](https://github.com/ITISFoundation/osparc-simcore/issues/2528)
- Refactor computational sidecar to remove dependencies to RabbitMQ/PostgresDB [#2530](https://github.com/ITISFoundation/osparc-simcore/issues/2530)
- Testing with Dask gateway on AWS cluster
### Open

**Comment by sanderegg** [comment]
## Update on sprint [Anti-PER](https://github.com/ITISFoundation/osparc-issues/milestone/24)

### Done
- Replacing dynamic sidecar proxy from Traefik to [Caddy](https://caddyserver.com/) for faster start [#2597](https://github.com/ITISFoundation/osparc-simcore/issues/2597)
- Allow node_ports package to create and get presigned links in storage for delayed upload and downloads by the dask-sidecar micro-service [#2605](https://github.com/ITISFoundation/osparc-simcore/issues/2605)

### Ongoing
- Refactor computational sidecar to remove dependencies to RabbitMQ/PostgresDB [#2530](https://github.com/ITISFoundation/osparc-simcore/issues/2530) 99% completed
- Connect director-v2 with dask-gateway(s) [#2576](https://github.com/ITISFoundation/osparc-simcore/issues/2576)

### Open
- Setup Dask gateway on AWS cluster (easy setup, autoscale)
- Reliability, UI, register clusters

**Comment by sanderegg** [comment]
## Update on sprint [Meerkat](https://github.com/ITISFoundation/osparc-issues/milestone/25)

### Done
- new repository [osparc-dask-gateway](https://github.com/ITISFoundation/osparc-dask-gateway), Dask-gateway with oSparc backend, create a Dask-sidecar for each worker (a user owns a cluster, a user deploy the osparc-dask-gateway, a user registers the gateway in oSparc)
- oSparc: 
  - a user can register a cluster providing an entrypoint and user/password
  - a user may share the registered cluster among other users/groups
  - keeps a pool of connections to the internal cluster and any number of external osparc-dask-gateways
  - sends pipeline of computational tasks to any cluster
  - receives logs, results from any cluster
- scaling:
  - user can add/remove machines manually to already running cluster
  - dask-gateway will use the machines accordingly
### Ongoing
- osparc-dask-gateway: SSL entrypoint, authentications, simplify deployment
- oSparc:
  - improve UI
  - test connection with cluster (provides feedback in case of issue/loss)
  - show cluster capabilities, running tasks
  - handle closed-source services
 - scaling:
   - provide auto-scaling on AWS
### Open

**Comment by sanderegg** [comment]
## Update on sprint [Rudolph](https://github.com/ITISFoundation/osparc-issues/milestone/26)

### Done
- ITISFoundation/osparc-dask-gateway#16: oSparc-dask-gateway now available for x86, ARMv7 and ARM64, based on dask-gateway *Database Backend*, migrated to python 3.9
- ITISFoundation/osparc-simcore#2747
### Bug fixes
### Changed

### Open issue / ongoing
- ITISFoundation/osparc-simcore#2477

**Comment by sanderegg** [comment]
## Update on sprint [Rudolph](https://github.com/ITISFoundation/osparc-issues/milestone/27)

### Done
- investigating persistency in dask-scheduler, reactions with restarts in director-v2 or dask-scheduler or dask-sidecar
### Bug fixes
### Changed
### Open issue / ongoing
- ITISFoundation/osparc-simcore#2477:
  - ITISFoundation/osparc-simcore#2798

**Comment by sanderegg** [comment]
## Update on sprint [E. Shackleton](https://github.com/ITISFoundation/osparc-issues/milestone/28)

### Done
### Bug fixes
### Changed
### Open issue / ongoing
- ITISFoundation/osparc-simcore#2477:
  - ITISFoundation/osparc-simcore#2798
  - ITISFoundation/osparc-simcore#2781
  - add HTTPS to connections with dask-gateway
  - run public services available on dockerhub on external gateways
  - auto-scaling in AWS

**Comment by sanderegg** [comment]
## Update on sprint [E. Shackleton](https://github.com/ITISFoundation/osparc-issues/milestone/29)

### Done
- ITISFoundation/osparc-simcore#2922
- ITISFoundation/osparc-simcore#2940
### Bug fixes
### Changed
### Open issue / ongoing
- ITISFoundation/osparc-simcore#2477:
  - add HTTPS to connections with dask-gateway
  - run public services available on dockerhub on external gateways
  - auto-scaling in AWS

**Comment by mrnicegyu11** [comment]
See related autoscaling cases:
- https://github.com/ITISFoundation/osparc-issues/issues/657
- https://github.com/ITISFoundation/osparc-issues/issues/656
