### ISSUE TITLE
S-D22.4 Meta-Modeling optimizer module Y4M12

### ISSUE THREAD

**Issue by KZzizzle** [ITISFoundation/osparc-issues#355]
22.4. An optimizer module exists that enables finding parameters that maximize a specified simulated quantity of interest within a provided parameter range. Dependencies between parameters can be specified. While the initial implementation will provide a general purpose, global optimizer, the underlying framework will be implemented flexibly, to readily permit extension by more specialized optimization approaches. **Y4M12**

**Comment by elisabettai** [comment]
As a use-case, we should now use CB's one

**Comment by pcrespov** [comment]
## Goal for sprint [Katherine Switzer](https://github.com/ITISFoundation/osparc-issues/milestone/36)

- ITISFoundation/osparc-simcore#3418
   - Finalize integration in OOIL
- [ ] review design
- [ ] create API to inject and execute new configurations 
- [ ] create ‘master' study where collected results can be further processed through pipeline

**Comment by pcrespov** [comment]
## Update on sprint [Katherine Switzer](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20221114_KatherineSwitzer.md)

### Done
- design example with Cedric

### Ongoing
- create API to inject and execute new configurations
    -  https://github.com/ITISFoundation/osparc-simcore/pull/3504  

### Open
- create ‘master' study where collected results can be further processed through pipeline

**Comment by pcrespov** [comment]
## Goal for sprint [Athena](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20221209_Athena.md)

- https://github.com/ITISFoundation/cookiecutter-osparc-service/pull/93
- https://github.com/ITISFoundation/cookiecutter-osparc-service/pull/94
- [ ] create API to inject and execute new configurations
   - https://github.com/ITISFoundation/osparc-simcore/pull/3536 
- [ ] create ‘master' study where collected results can be further processed through pipeline

- OOIL
		- https://github.com/ITISFoundation/cookiecutter-osparc-service/pull/93
		- https://github.com/ITISFoundation/cookiecutter-osparc-service/pull/94
		- [ ] release lifecycle with MaG (remember to create an issue!)
	- optimizer
		- [ ] [Draft code-to-workbench concept for meta-meeting on Wed #3554](https://github.com/ITISFoundation/osparc-simcore/issues/3554)
		- [ ]  [WIP: Is355/optimizer clone projects](https://github.com/ITISFoundation/osparc-simcore/pull/3536)
		- [ ] optimization (run, log, progress, stop)
		- [ ] delayed deletion

**Comment by pcrespov** [comment]
## Update on sprint [Athena](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20221202_Athena.md)

### Done
- First full workflow for  "Fast service integration" ( part of https://github.com/ITISFoundation/osparc-issues/issues/693 )

### Ongoing

- Extend API: create API to inject and execute new configurations
   - https://github.com/ITISFoundation/osparc-simcore/pull/3536 
- Improvements on "fast service integration"

### Open
- Extend API: create API to inject and execute new configurations
   - optimization (run, log, progress, stop). 
   - delayed deletion
- create ‘primary' study where collected results can be further processed through pipeline
