### ISSUE TITLE
modeler & postpro completeness

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-issues#363]
priority:
- [x] color bar for viewers
- [x] slice field viewer: the slice number and the slice position are decoupled and do different things (e.g., placing the slice vs. cutting the model). some of the settings do not work (e.g., transparency).
- [ ] iso-surface viewer
- [x] there seem to be situations, where not all entities are displayed in the tree
- [x] more icons

------------------------
- [ ] persistency

postpro service
---------------
technically missing: non-viewers, connection of components, color-bar, bugs, off screen performance

modeler service
---------------

**Comment by pcrespov** [comment]
Notes during PM1:
- Continuous list of issues on model&postpro
