### ISSUE TITLE
M1–9 Cybersecurity and privacy

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-issues#509]
During the first SPARC phase, little consideration has been given to cybersecurity and privacy. It is now necessary to ensure that users cannot abuse the power of scripting services (JupyterLab, etc.) and that data is secure. This requires all user services to run in complete isolation from the platform (currently not the case for dynamic services). Also, automated vulnerability checks for third-party libraries will be established. For patient data images we want to make sure all data is de-identifed (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7104701/#s6title) when uploaded into the platform.
The exact implementation pathway remains to be determined, but is likely to address the following: service isolation, 3rd party libraries vulnerabilities, Docker image vulnerabilities, AppArmor, strict resource management, enhanced authentication system (HIPAA is for now out of reach).

**Deliverable: referenceable documentation of the platform cyber-security and privacy functionality (Q3)**

- [ ] service isolation
- [x] 3rd party libraries vulnerabilities
- [ ] Docker image vulnerabilities
- [ ] AppArmor
- [ ] strict resource management
- [ ] enhanced authentication system

**Comment by mrnicegyu11** [comment]
By fine-graining the security-headers sent upon initial connection to `osparc.io`, we were able to increase our "grade" given by the `Mozilla Observatory` from an F to a grade B: https://observatory.mozilla.org/analyze/osparc.io 

![image](https://user-images.githubusercontent.com/8209087/153021454-0a745393-fbf3-4214-8652-128a3495b5e9.png)

One can rationalize these security-headers as some promises oSparc makes to the browser, like "I will not serve you javascript over a non-SSL conenction" or "I will serve you only iframes that come from subdomains of `osparc.io`". This decreases the attack vector of hypothetical attackers abusing potential security vulnerabilities, as the client browser will not let `osparc.io`, or an attacker abusing some part of `osparc.io`, break these promises afterwards. 

Due to how oSparc works (serving services in frames, etc.), we cannot achieve grade A by design it seems. A grade B+ might be achievable in principle, but would require some (lots?) of cleanup in oSparc.

**Comment by mrnicegyu11** [comment]
We have added the security and vulnerability analysis tool `snyk` [https://snyk.io/](https://snyk.io/) to our docker-containers and open-source code repositories. It automatically checks for known vulnerabilities, assesses their criticality and shows if there are known exploits (--> hacks) in the wild for them. To this end, especially external code dependencies are evaluated as it seems. We will monitor the results from snyk and try to address as many vulnerabilities as possible. Disclaimer: For some known vulnerabilities in external code dependencies, there are no fixes available yet, so it is hardly possible to reach perfect security (0 vulns)
