### ISSUE TITLE
S4L:web, Milestone II, Onboarding User Group II

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-issues#554]
According to the roadmap/plan and as outlined in the BBL II, **onboarding of user group II for S4L:web (Milestone II)**:

- [ ] Finalize code basis for EM LF-Neuro (for testing S4L toy-workflows)
- [x] Finalize code basis for EM FDTD (for testing S4L toy-workflows)
- [x] Onboarding of user group "general workflows, guided mode" (Taylor, Antonino, Cedric, Lena, Cosimo, Tolga)
- [x] Onboarding of user group "EM LF-Neuro" (Taylor, Antonino)
- [x] Onboarding of user group "EM FDTD" (Sylvain, Lena, Cosimo)

- All via s4l-staging.speag.com
- General support for onboarding, collection of feedback, etc.
