### ISSUE TITLE
control, provide, and track resources

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-issues#576]
this is a parent case that needs to be related to suitable sub-cases.

we need functionality that
```[tasklist]
### Tasks
- [ ] controls the resources that can be used by a specific user / user group (CPU & GPU time, memory cap, access to specific HW)
  - likely tied also to specific services (e.g., GPU resource available to a specific user for a specific isolve computational service)
- [ ] permits to reserve resources for exclusive usage (e.g., by requesting dedicated AWS machines that are then added to the swarm and for which the user has exclusive usage rights; or by bringing own machines that are coupled through dask gateways)
- [ ] monitors used resources for future cost offsetting / charging
- [ ] permits administration of resource access (initially maybe by the support team, but later also by users). Webpage could be standalone (at least initially)
```

**Comment by mguidon** [comment]
## Status Report after Schumann

- [ ] Initial discussion
- [ ] Apply identical resources to all services (limits and reservations)
- [ ] Allow user to dynamically overwrite
- [ ] Use gateway on AWS with autoscaling
- [ ] Autoscaling for dyn. services nodes

**Comment by pcrespov** [comment]
RUT covers this
