### ISSUE TITLE
Autoscaling - Dynamic Services

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-issues#657]
Auto-scale the docker swarm nodes for the dynamic services.
- Reuse the tooling created in #656 for scaling of the cluster
- The metrics must come from the docker swarm and has to include GPU
- This will require to assign/consume proper numbers for the available VRAM/AIRAM
- This will result in users having to wait for machines coming available and they need to be notified about that.
- Use case will be running tons of sim4life:web instances

**Comment by mrnicegyu11** [comment]
# Dynamic Services Autoscaling
## Agnostic Autoscaling [Scales when there are services pending, no customization]
### [x] Proof of Concept 
### [ ] First Version
- [ ] Implement: Upper limit for total number of auto-scaled machines
- [ ] Gracefully handle: No more machines on AWS available
- [ ] Robustness: Check multiple times that no service is run
- [ ] Mitigate: Swarm schedules services on all nodes equally (possibly: use `default_machine` label placement constraint and a label_replacement microservice)
- [ ] Testing: Extensive testing on staging
- [ ] Logging: Send logs of autoscaling service to graylog
### Metrics:
- [ ] Aggregate metrics about autoscaling: Add prometheus endpoint
### Failure scenarios (1. simulate, 2. mitigate, 3. test mitigation):
- [ ] AWS has no resources available for the desired machine
- [ ] AWS  has no resources available at all
- [ ] downscaling (deletion of machine), but work wasn't properly saved to S3
- [ ] Too many hosts or too powerful host added (cost spike due to bugs)
- [ ] User needing more space HDD space 
- [ ] Node that runs the autoscaling microservice fails
### Enhancements:
- [ ] Augment in-house deployments with auto-scaled AWS nodes (requires VPN solution)

**Comment by sanderegg** [comment]
## Goal for sprint [Katherine Switzer](https://github.com/ITISFoundation/osparc-issues/milestone/36)
- show scaling of nodes in the frontend
- run autoscaling app background task
- --> start a service and wait for a new node to start

**Comment by sanderegg** [comment]
## Update on sprint [Katherine Switzer](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20221114_KatherineSwitzer.md)

- New Autoscaling application in osparc-simcore stack
  - unit tested
  - allows backend devs to contribute
  - migration still in progress
- Frontend notifications in progress ([#3502](https://github.com/ITISFoundation/osparc-simcore/pull/3502))

**Comment by sanderegg** [comment]
-Finish migration of script into osparc-simcore SAN
- connect with the frontend
- test on AWS staging by deploying the full stack (reconfigure deployer)
-

**Comment by mrnicegyu11** [comment]
The following tasks also have to be tackled, these need to be done on the DevOps side:
- [ ] Determine how to provide the AMI image for autoscaled nodes (talk to @mguidon )
- [ ] Increase machine linux password security
- [ ] Create aws functional user for autoscaling task with limited capabilities

**Comment by sanderegg** [comment]
## Update on sprint [Athena](https://github.com/ITISFoundation/osparc-issues/milestone/37)

### Done
  - https://github.com/ITISFoundation/osparc-simcore/issues/3558
  - https://github.com/ITISFoundation/osparc-simcore/pull/3617
  - https://github.com/ITISFoundation/osparc-simcore/pull/3622
  - Early testing on AWS staging by deploying the autoscaling app
  - All sim4life-light-dy shall start on auto-scaled nodes (through changes in DB) - POC done
### Ongoing
  - https://github.com/ITISFoundation/osparc-simcore/pull/3620
  - Feedback in the osparc UI
  - Handle autoscaling app restarts
  - Handle multiple autoscaling apps running in parallel
  - Gracefully handle when AWS cannot create new machines (user feedback, take next possible EC2 instance)
  - add VRAM, Generic resources handling (not really useful for current use-case)

  - apply to AWS to get more vCPUs [ALL]

2.
- metrics (prometheus)
- Robustness to bugs in dy-sidecar (restarts, manual killing,...)

**Comment by sanderegg** [comment]
## Goal for sprint [Zefram Cochrane](https://github.com/ITISFoundation/osparc-issues/milestone/38)
- https://github.com/ITISFoundation/osparc-simcore/pull/3631
- https://github.com/ITISFoundation/osparc-simcore/issues/3600
- https://github.com/ITISFoundation/osparc-simcore/issues/3627
- https://github.com/ITISFoundation/osparc-simcore/issues/3628
-------------------------------------------- Autoscaling heavier testing ready -------------------------------------
- https://github.com/ITISFoundation/osparc-simcore/issues/3629
- https://github.com/ITISFoundation/osparc-simcore/issues/3559
- https://github.com/ITISFoundation/osparc-simcore/issues/3341
- https://github.com/ITISFoundation/osparc-simcore/issues/3663
- DevOPS: Create AWS EC2 specific user with restricted access rights for autoscaling service
- DevOPS: Create AMI with preloaded images (dynamic-sidecar, portainer-agent, cadvisor, node exporter, nvidia-exporter?, service images), create an automatic system if possible

**Comment by sanderegg** [comment]
## Update on sprint [Zefram Cochrane](https://github.com/ITISFoundation/osparc-issues/milestone/38)

### Done
  - [Upgrade of python-socketio to latest](https://github.com/ITISFoundation/osparc-simcore/pull/3631)
  - [Refactor usage of aiodocker/aioboto3 libraries in autoscaling service](https://github.com/ITISFoundation/osparc-simcore/issues/3600)
  - https://github.com/ITISFoundation/osparc-simcore/issues/3627
  - https://github.com/ITISFoundation/osparc-simcore/issues/3628
  - https://github.com/ITISFoundation/osparc-simcore/issues/3689
  - https://github.com/ITISFoundation/osparc-simcore/issues/3722
### Ongoing
  - https://github.com/ITISFoundation/osparc-simcore/issues/3341
  - https://github.com/ITISFoundation/osparc-simcore/issues/3663
### Next steps
  - https://github.com/ITISFoundation/osparc-simcore/issues/3629
  - https://github.com/ITISFoundation/osparc-simcore/issues/3559
  - DevOPS: Create AWS EC2 specific user with restricted access rights for autoscaling service
  - DevOPS: Create AMI with preloaded images (dynamic-sidecar, portainer-agent, cadvisor, node exporter, nvidia-exporter?, 
    service images), create an automatic system if possible

**Comment by sanderegg** [comment]
## Update on sprint [Resistance is Futile](https://github.com/ITISFoundation/osparc-issues/milestone/39)

### Done
  - https://github.com/ITISFoundation/osparc-simcore/issues/3341
     - https://github.com/ITISFoundation/osparc-simcore/issues/3773
  - https://github.com/ITISFoundation/osparc-simcore/issues/3743
    - https://github.com/ITISFoundation/osparc-simcore/issues/3747
  - https://github.com/ITISFoundation/osparc-simcore/issues/3746
  - https://github.com/ITISFoundation/osparc-simcore/issues/3789
  - https://github.com/ITISFoundation/osparc-simcore/issues/3790
  - https://github.com/ITISFoundation/osparc-simcore/issues/3799
  - https://github.com/ITISFoundation/osparc-simcore/issues/3804


### Ongoing
  - https://github.com/ITISFoundation/osparc-simcore/issues/3663
  - https://github.com/ITISFoundation/osparc-simcore/issues/3876
### Next steps
  - https://github.com/ITISFoundation/osparc-simcore/issues/3629
  - https://github.com/ITISFoundation/osparc-simcore/issues/3559
  - https://github.com/ITISFoundation/osparc-simcore/issues/3808
  - DevOPS: Create AWS EC2 specific user with restricted access rights for autoscaling service
  - DevOPS: Create AMI with preloaded images (dynamic-sidecar, portainer-agent, cadvisor, node exporter, nvidia-exporter?, 
    service images), create an automatic system if possible

**Comment by sanderegg** [comment]
## Goal for sprint [Mithril](https://github.com/ITISFoundation/osparc-issues/milestone/40)
- https://github.com/ITISFoundation/osparc-simcore/pull/3631
- https://github.com/ITISFoundation/osparc-simcore/issues/3600
- https://github.com/ITISFoundation/osparc-simcore/issues/3627
- https://github.com/ITISFoundation/osparc-simcore/issues/3628
-------------------------------------------- Autoscaling heavier testing ready -------------------------------------
- https://github.com/ITISFoundation/osparc-simcore/issues/3629
- https://github.com/ITISFoundation/osparc-simcore/issues/3559
- https://github.com/ITISFoundation/osparc-simcore/issues/3341
- https://github.com/ITISFoundation/osparc-simcore/issues/3663
- DevOPS: Create AWS EC2 specific user with restricted access rights for autoscaling service
- DevOPS: Create AMI with preloaded images (dynamic-sidecar, portainer-agent, cadvisor, node exporter, nvidia-exporter?, service images), create an automatic system if possible

**Comment by sanderegg** [comment]
@drniiken for info these are my latest tests with different combinations as of yesterday in staging-AWS (staging.osparc.io) using the latest code. (*not yet in production*)


# testing s4l-lite 2.0.106 startup times

- times [min:sec] coming from the osparc logs
- fresh means the machine is created on demand (no buffer)
- buffer means the machine was pre-created and is available
- no pre-pull means nothing is pulled on machine start
- osp pre-pull means only monitoring docker images are pulled on start
- ops + 2.0.106 means monitoring images and the largest image of s4l-lite is pulled on start


|type| service-started | new machine ready | sidecar first log | S4l-lite ready |
| - |------------------|------------------|-------------------|----------------|
| fresh no pre-pull | 00:00 | 02:18 | 04:30 | 07:09 |
| fresh ops pre-pull | 00:00        | 02:21          | 03:53          | 06:37       |
| fresh full pre-pull | 00:00 |02:15|03:55|06:31|
| buffer no pre-pull | 00:00|00:09|01:42|04:18
| buffer full pre-pull|00:00|00:03|01:37|02:08
||  |  | ||
| **warm drained node (standard)**| 00:00 | 00:05|00:40|~01:00|
