### ISSUE TITLE
DRC & o2S API

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-issues#668]
- Extend existing APIs (computational API, study creation and access, platform API), add new APIs (progress API, import/export API) as required by users and in support of the DRC APIs, exposing: 
  - queuering of service & study input/output port descriptions
  - search for compatible services to a data item (initially based on mime-type, potentially later extensible based on file-level meta-data annotation)
  - launching of computational study with given input parameters / data; initially focusing on similar use-cases as the Portal-launched simulations
- Access to logs after job was run 
- API for import/export of data
- Instantiation of a study that contains a file import service that already points to the given data-item and an attached visualization/analysis/processing user-requested service (user-login dependant)
- The above functionality accepting data and input will support data pointers from the DRC API

Deliverable: The above described o²S²PARC / DRC API (and Python client) functionality
```[tasklist]
### Tasks
- [ ] Upgrade version when new client (with functionality above) is released @bisgaard-itis

```
```[tasklist]
### Baklava
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/710
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/681
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/690
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/692
```

```[tasklist]
### Watermelon
- [ ] https://github.com/nih-sparc/sparc.client/pull/7
- [ ] https://github.com/nih-sparc/sparc.client/pull/19
- [ ] https://github.com/nih-sparc/sparc.client/pull/17/
```

**Comment by elisabettai** [comment]
@pcrespov, is there anything worth mentioning on the call on January 31?

**Comment by pcrespov** [comment]
## Update on sprint [Resistance Is Futile](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230220_ResistanceIsFutile.md)

### Done
  - Meeting on Tuesday, January 31, 2023 8:00 PM - 8:30 PM
### Ongoing
  -  Reviews on NIH's sparc.client repo
  - https://github.com/nih-sparc/sparc.client/pull/7

**Comment by pcrespov** [comment]
## Goal for sprint [Pastel de Nata](https://github.com/ITISFoundation/osparc-issues/milestone/45)
- ...

**Comment by elisabettai** [comment]
@pcrespov, I've checked deadlines for this: the first task of the list "Implement base-client in nih-sparc api over ``osparc==0.5.0``" should ideally be completed by the end of the Watermelon sprint.

I wanted to update the task list at the top, but I'm not sure if the first point depends on the second.

**Comment by bisgaard-itis** [comment]
> @pcrespov, I've checked deadlines for this: the first task of the list "Implement base-client in nih-sparc api over `osparc==0.5.0`" should ideally be completed by the end of the Watermelon sprint.
> 
> I wanted to update the task list at the top, but I'm not sure if the first point depends on the second.

I believe this is what you suggest I work on (right @pcrespov?). Do I understand correctly from the osparc sprint board that the watermelon sprint runs until July 14?

**Comment by pcrespov** [comment]
> 
@elisabettai yes, as I updated in the daily, this will be the case.

@bisgaard-itis , not July 7.Check the milestone deadline https://github.com/ITISFoundation/osparc-issues/milestone/46

**Comment by bisgaard-itis** [comment]
> > 
> 
> @elisabettai yes, as I updated in the daily, this will be the case.
> 
> @bisgaard-itis , not July 7.Check the milestone deadline https://github.com/ITISFoundation/osparc-issues/milestone/46. I will start today and if I need extra help I will ask you :-)

Perfect. Thanks.
Just let me know

**Comment by pcrespov** [comment]
# Update [Watermelon](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230707_Watermelon.md)
-

**Comment by bisgaard-itis** [comment]
# Update [Sundae](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230814_Sundae.md)

- Only missing a PR review to merge https://github.com/nih-sparc/sparc.client/pull/17 which will expose all functionality from the API server necessary to run a variant of the [BasicTutorial](https://itisfoundation.github.io/osparc-simcore-clients/#/clients/python/artifacts/docs/BasicTutorial)
- We have a concrete user story (https://github.com/ITISFoundation/osparc-simcore-clients/issues/53) for a tutorial displaying cross-functionalities between the different cores.

**Comment by elisabettai** [comment]
@bisgaard-itis, this looks completed to me as far as the description/NIH is concerned.

I only see this open task: 
- [ ] Upgrade version when new client (with functionality above) is released [@bisgaard-itis](https://github.com/bisgaard-itis)

Do you think is still relevant? 
fyi, we also have these new cases, partially related
#1088 
#1095

**Comment by bisgaard-itis** [comment]
> @bisgaard-itis, this looks completed to me as far as the description/NIH is concerned.
> 
> I only see this open task:
> 
>     * [ ]  Upgrade version when new client (with functionality above) is released [@bisgaard-itis](https://github.com/bisgaard-itis)
> 
> 
> Do you think is still relevant? fyi, we also have these new cases, partially related #1088 #1095

I think this is still relevant to the extend that when we release a new `osparc` python client we should ensure the sparc.client still works with the new client. Which is of course the case as long as we don't break backwards compatibility. But I am not sure how much functionality we need to expose in sparc.client. Hence, I guess we can remove that task for now

**Comment by elisabettai** [comment]
Ok. Thanks @bisgaard-itis, I leave it open for the moment while thinking where what you described should go.

Curiosity: do we already know when we want to release a new version of the Python client? I guess server side we have tons of new things already.

**Comment by bisgaard-itis** [comment]
@elisabettai We discussed several times about releasing a new python client, but I don't think we settled on a date yet. It might make sense to wait until we have sufficient study functionality for Cedric to do his work 🤔

**Comment by elisabettai** [comment]
I close this for now. It sounds that the new remaining task is release a new client with new functionality (e.g. the one for studies).

This is probably going to be needed when #767 is ready or for #1088.
