### ISSUE TITLE
TIP - FollowUp Items

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-issues#670]
**Follow Up Items for TIP**

- demo license style usage
- S4L: automatically load slice field viewer
- statistics on how people are using it
- get rid of the optimizer (do all in one service)

- better optimization in general, replace sweeper (for later, once we know how this packages)

backend (3d in total, if all goes fine)
- sync with latest simphony master
- test for Mel's code
- License Server
- oil, properly integrate (least important), onboarding of users facilitate (#693)

to keep in mind:
- [x] more anatomical models
- [ ] low resolution library for optimization, linearized functional for preoptimization...
- [ ] personalization
- [x] more than two channels
- [ ] library of preoptimized targets

**Comment by pcrespov** [comment]
## Update on sprint [Vaporwave](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20221007_Vaporwave.md)

### Done
- https://github.com/ITISFoundation/osparc-simcore/pull/3349
- https://github.com/ITISFoundation/osparc-simcore/pull/3383
- https://github.com/ITISFoundation/osparc-simcore/issues/3318

### Ongoing

### Open

**Comment by esraneufeld** [comment]
- [ ] more anatomical models
- [ ] low resolution library for optimization, linearized functional for preoptimization...
- [ ] personalization
- [ ] more than two channels
- [ ] library of preoptimized targets

**Comment by pcrespov** [comment]
## Goal for sprint [Katherine Switzer](https://github.com/ITISFoundation/osparc-issues/milestone/36)

- ITISFoundation/osparc-simcore#3318
- ITISFoundation/osparc-simcore#3305
- #679 ???

**Comment by pcrespov** [comment]
## Goal for sprint [Athema](https://github.com/ITISFoundation/osparc-issues/milestone/37)

- ITISFoundation/osparc-simcore#3318
- ITISFoundation/osparc-simcore#3305

### Review demo
- resend confirmation

**Comment by Konohana0608** [comment]
all the tasks have either been completed or added to other issues.
