### ISSUE TITLE
M9 SDS and cMIS (model-related metadata exposed on the Portal)

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#673]
Work with K-CORE (lead) and the other Cores on display of model-related meta-data on the Portal.
The presentation of model-related metadata shall be consistent with the metadata section for published data on the Portal.

This will likely involve:
- Adaptation of the SDS and cMIS (in collaboration with K-CORE and where needed the other COREs). For EI, EN.
- An extension of the export functionality on o²S²PARC to export o²S²PARC metadata specific to the computational modeling side into the metadata files stored in the SDS. For PC, ANE

Deliverable: All o²S²PARC functionality required to power the display of the above-mentioned metadata on the SPARC Portal. Contribution to the Portal-side implementation.
Deadline: Y6Q3

[Wrike Y6-M1.3](https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=916225133&pid=916188668&cid=720993193) 

Update on March 2023: In this [wrike ticket](https://www.wrike.com/open.htm?id=1074347700) we provided a temporary cMIS file to start testing how it will be displayed on the SPARC Portal

```[tasklist]
### Quilmes
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1138
- [ ] Export the latest [code_description_example_dataset_2023-08-28.xlsx](https://github.com/ITISFoundation/osparc-issues/files/12549627/code_description_example_dataset_2023-08-28.xlsx)
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4216
```

```[tasklist]
### Pastel de Nata
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4213
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4339
```

```[tasklist]
### Watermelon
- [x] Re-enable feature and cleanup front-end @GitHK with some help from @odeimaiz
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/3183
```

```[tasklist]
### Sundae
- [x] Adaptation of the SDS and cMIS (in collaboration with K-CORE and where needed the other COREs) @esraneufeld @elisabettai
- [x] Apply cMIS to an example dataset (will use [this template](https://osparc.io/study/65a52908-1b13-11ee-9cd1-02420a0b1bed)) @elisabettai
```

**Comment by pcrespov** [comment]
## Goal for sprint [Mithril](https://github.com/ITISFoundation/osparc-issues/milestone/40)
-

**Comment by pcrespov** [comment]
@sanderegg @elisabettai  we should consider thisone because it is next deadline!

**Comment by GitHK** [comment]
Pastel de Nata:
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4213

**Comment by GitHK** [comment]
## Update on sprint [Pastel de Nata](https://github.com/ITISFoundation/osparc-issues/milestone/45)

Ongoing:
- https://github.com/ITISFoundation/osparc-simcore/issues/4213

**Comment by esraneufeld** [comment]
@esraneufeld will provide the Excel sheet to @GitHK as soon as the OK from K-Core arrives

**Comment by elisabettai** [comment]
In the Q3 reporting, we promised to finalize this by end of July

**Comment by elisabettai** [comment]
## Update for sprint [Sundae](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230814_Sundae.md)

### Done
- Updated the cMIS with an example use-case
- Got approval from K-Core on the cMIS format
- Send the cMIS to MAP-Core (Alan) who will shortly apply it to one of his models
- Started drafting a response for the Standardization Commitee

### Todo
- Finalize the response
- Publish cMIS on the Portal before submitting the response? To discuss with EN.
- Get more examples of application of the cMIS from external users? NP? Max (our Vienna friend)? To discuss with EN.
- Update the export functionality in oSPARC
- Update the oSPARC frontend for the new formulation/format of the Ten Simple Rules

fyi @GitHK, in case you want to add something or we need to mention it at the review.
