### ISSUE TITLE
M1-12 Portal development work 

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#674]
Original title on Wrike: [Meet Unplanned Feature Requests that Align with DRC Priorities via the CCB Process](https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=916223337&pid=916188668&cid=720993193)

Deliverable: 10 points per SPRINT to contribute to (unplanned) Portal development work.
Deadline: Month 1–12 (continuous task)

```[tasklist]
## Milestone Work
- [x] [Include oSPARC services on Tools & Resources](https://www.wrike.com/open.htm?id=1073800205)
- [x] Follow up of (https://github.com/ITISFoundation/osparc-simcore/pull/4043)
- [x] https://www.wrike.com/workspace.htm?acc=3203588#/inbox/task/916241916
- [x] https://www.wrike.com/workspace.htm?acc=3203588#/inbox/task/1074321820
```

## Year 6

```[tasklist]
### sprint 31 [backlog](https://www.wrike.com/open.htm?id=987366879) \[08/09/2023]
- [x] [SPARC Feedback Submission: The oSPARC button on Files tab does not work](https://www.wrike.com/open.htm?id=1183457890)(1 Point)
- [x] [Align File level metadata pages to always show the viewer on top](https://www.wrike.com/open.htm?id=955702860)(1 Point)
- [ ] [Prefill form contact information when submitting another request](https://www.wrike.com/open.htm?id=1161704527)(3 Points)
```

```[tasklist]
### sprint 30 [backlog](https://www.wrike.com/open.htm?id=987365472) \[31/07/2023]
- [x] [Implement modifications that launches the SDS viewer from a dataset landing page with the dataset loaded.](https://www.wrike.com/open.htm?id=1141951787)(2 Points)
- [x] [APS: Homepage - Change of section title](https://www.wrike.com/open.htm?id=1119233920)(1 Point)
- [x] [APS: Additional padding above "“The following results were discovered for the other categories” - faceted browse.](https://www.wrike.com/open.htm?id=1119240774)(1 Point)
- [x] [APS: Some datasets aren't linked to available scaffold.](https://www.wrike.com/open.htm?id=1119242779)(2 Points)
```

```[tasklist]
### sprint 29 [backlog](https://www.wrike.com/open.htm?id=987364060) \[23/06/2023]
- [x] [Broken Images for Dataset 54](https://www.wrike.com/open.htm?id=1023216206)(3 Points)
- [x] [Dataset 252: Video links not working](https://www.wrike.com/open.htm?id=934711095)(3 Points)
- [x] [Unable to view the movies for dataset 73 and 175 accessed via the Gallery in Safari but able to view via Chrome.](https://www.wrike.com/open.htm?id=840919894)(3 Points)
```

```[tasklist]
### sprint 28 [backlog](https://www.wrike.com/open.htm?id=987362481) \[12/05/2023]
- [x] [Allow the Gallery Videos to select a static image to display in the thumbnail.](https://www.wrike.com/open.htm?id=984390363) (3 Points)
- [x] [Bug: Consistent action when clicking on dataset DOIs](https://www.wrike.com/open.htm?id=1053565812)(1 Point)
- [x] [The Tools&Resources search on the homepage header lands in Biological Browse Category](https://www.wrike.com/open.htm?id=1050960119)(1 Point)
- [x] [Provide a species facet for scaffolds and computational models](https://www.wrike.com/open.htm?id=1080628946)(2 Points)
```

```[tasklist]
### sprint 27 [backlog](https://www.wrike.com/open.htm?id=987358802) [03/04/2023]
- [x] [Mailchimp sign-up URL](https://www.wrike.com/open.htm?id=1064436312) (1 Point)
- [x] [Rename anatomical focus  to focus in project section](https://www.wrike.com/open.htm?id=1018237582) (1 Point)
- [x] [Request access to embargoed data](https://www.wrike.com/open.htm?id=1043689039) (1 Point)
- [x] [The News & Event page does not display anatomical structure for Community Spotlight items](https://www.wrike.com/open.htm?id=1043784426) (2 Points)
```
```[tasklist]
### sprint 26 [backlog](https://www.wrike.com/open.htm?id=987354990) [20/02/2023]
- [x] [Add re3Data badge to easy to see location(s)](https://www.wrike.com/open.htm?id=1031542283) (2 Points)
- [x] [Allow the Gallery Videos to select a static image to display in the thumbnail.](https://www.wrike.com/open.htm?id=984390363) (5 Points)
- [x] [Make entire button for View Project and View Dataset on the Homepage clickable, not just text area](https://www.wrike.com/open.htm?id=1030991543) (2 Points)
```
```[tasklist]
### sprint 25 [backlog](https://www.wrike.com/open.htm?id=985103505) [09/01/2023]
- [x] [Tools and Resources Faceted Browse: Include tool/resource creator name and email in search](https://www.wrike.com/open.htm?id=966743849) (3 Points)
- [x] [News and Events Submission Form: Increase the target to the entire button, not just the text on the button.](https://www.wrike.com/open.htm?id=967369259) (2 Points)
- [x] [Feature request: On the Search/FB pages for News & Events and Tools & Resources, add the ability to submit a form.](https://www.wrike.com/open.htm?id=1014552144) (2 Points)
- [x] [Make office hours documented in help center open in a tab](https://www.wrike.com/open.htm?id=1018012768) (1 Point)
```

```[tasklist]
### sprint 24 [backlog](https://www.wrike.com/open.htm?id=953011753) [28/11/2022]
- [x] [EB: Highlight search term results in dataset details](https://www.wrike.com/open.htm?id=943245360) (5 Points)
- [x] [ISAN: Make help center open in a new tab](https://www.wrike.com/open.htm?id=970463403) (1 Point)
- [x] [Planning: how to generate thumbnails for existing videos](https://www.wrike.com/open.htm?id=984522431) (3 Points)
```

```[tasklist]
### sprint 23 [backlog](https://www.wrike.com/open.htm?id=825399023) [17/10/2022]
- [x] [Consolidate Paths for File-details: Implementation](https://www.wrike.com/open.htm?id=896884564) (3 Points)
- [x] [API endpoint for returning overall SPARC metrics](https://www.wrike.com/open.htm?id=945100299) (5 Points)
- [x] [Please provide Markdown functionality in the description of resources so that we can provide URLs in this text box](https://www.wrike.com/open.htm?id=952119114) (2 Points)
```

**Comment by mguidon** [comment]
Great job. Thanks!

**Comment by ignapas** [comment]
### Sprint work
* [ ] [Broken Images for Dataset 54](https://www.wrike.com/open.htm?id=1023216206) (3 Points)
Caused by problems in Biolucida. I should be updated whenever this problem is solved and I can retest
* [x] [Dataset 252: Video links not working](https://www.wrike.com/open.htm?id=934711095) (3 points)
* [x] [Unable to view the movies for dataset 73 and 175 accessed via the Gallery in Safari but able to view via Chrome.](https://www.wrike.com/open.htm?id=840919894) (3 Points)
Workaround video encoding problem by showing a dialog informing the user about the problem, with the recommendation of downloading the video.
### Milestone work
* [x] All completed
### Past issues
* [x] [Allow the Gallery Videos to select a static image to display in the thumbnail.](https://www.wrike.com/open.htm?id=984390363) (3 Points)
Merged, testing will be tricky

**Comment by elisabettai** [comment]
@mguidon, @ignapas. Please close when the last task is completed and use #1080 (new case for Y7)
