### ISSUE TITLE
M1-12 Maintenance and DevOps

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#675]
(This is a task, not a milestone)
Continuously maintain o²S²PARC platform, harden, and increase stability and scalability to accommodate increased use.

For example: 
- enable scaling of selected core services through recently introduced modularization and plugin concept
- file-system performance boosting, especially for large files

Deliverable: monthly update slides as part of the NIH SIM-Core update meeting
Deadline: Month 1–12 (continuous task)

DETAILS IN https://github.com/orgs/ITISFoundation/projects/9/views/34

```[tasklist]
### Watermelon
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/172
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/173
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/176

```

```[tasklist]
### Sundae
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/176
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/200
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/190
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/215
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/248
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/250
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/258
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/262
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/274
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/276
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/278
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/282
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/287
```

```[tasklist]
### Baklava (ops)
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/pull/310
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/pull/312
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/pull/313
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/pull/314
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/319
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/pull/322
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/323
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/pull/329
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/332
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/333
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/pull/335
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/pull/338
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/pull/340
```

**Comment by elisabettai** [comment]
This is a continuation of #428, fresh start into Y6. Could also be used to write updates on DevOps side.

**Comment by pcrespov** [comment]
## Update on sprint [Vaporwave](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20221007_Vaporwave.md)

### Done

- Add: Seventh machine on master
- Prometheus: Update, Crash, Reasonings
- Expose PostgresDB: Enable inter-deployment copying script
- oSparc Infra changes: SSH-Hardening
- ITISFoundation/osparc-simcore#3358
- Create Mattermost Channel Alert for graylog
- Bugfix: Docker machine label changes
- E-Mail Script: Notify logged in users during maintenance
- Update logspout-gelf service to latest version and move to itisfoundation github & dockerhub
- Update grafana major version
- Upgrade of docker registry
- New release workflow

### Ongoing



### Open

**Comment by sanderegg** [comment]
## Goal for sprint [Katherine Switzer](https://github.com/ITISFoundation/osparc-issues/milestone/36)
- [osparc-issues#](https://github.com/ITISFoundation/osparc-issues/issues/644)

**Comment by mrnicegyu11** [comment]
For the review, for the shared ops/maintenance item, I have on my list done this sprint:
- Traefik Dashboard `/api` handling, which leads to not showing weird errors if a jupyter-service container dies  (thx EI)
- Add log-rotation to docker daemon (everywhere done)
- Dont run docker daemon on DEBUG (everywhere done
- Harmonize `/docker` mounts
- Added grafana dashboard
- Add e2e test for oSparc products an APIs
- Allow for cpu/RAM limits in simcore & ops services 
- Add pre-commit hooks and linting to opsarc-ops repo (thx PC)

**Comment by pcrespov** [comment]
## Goal for sprint [Athena](https://github.com/ITISFoundation/osparc-issues/milestone/37)
- https://github.com/ITISFoundation/osparc-simcore/issues/2410
- ...

**Comment by sanderegg** [comment]
## Update on sprint [Athena](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20221202_Athena.md)
### User support
### Security
### Bugfixes / Technical debt
### CI/CD
- https://github.com/ITISFoundation/osparc-simcore/pull/3480
### e2e testing
### Pre/releases during this sprint
- https://github.com/ITISFoundation/osparc-issues/issues/759
- https://github.com/ITISFoundation/osparc-issues/issues/771
- https://github.com/ITISFoundation/osparc-issues/issues/775
### Dependencies
- https://github.com/ITISFoundation/osparc-issues/issues/735
### DevOps


- https://github.com/ITISFoundation/osparc-simcore/issues/2410
- https://github.com/ITISFoundation/osparc-simcore/issues/2393
- https://github.com/ITISFoundation/osparc-issues/issues/594
- https://github.com/ITISFoundation/osparc-issues/issues/739

- https://github.com/ITISFoundation/osparc-simcore/issues/3421
- https://github.com/ITISFoundation/osparc-issues/issues/638
- https://github.com/ITISFoundation/osparc-simcore/issues/2625
- https://github.com/ITISFoundation/osparc-simcore/pull/3502

- https://github.com/ITISFoundation/osparc-simcore/issues/3447

- https://github.com/ITISFoundation/osparc-simcore/pull/3553

**Comment by sanderegg** [comment]
## Goal for sprint [Zefram Cochrane](https://github.com/ITISFoundation/osparc-issues/milestone/38)
- Staging releases
- Production releases
- Remove openapi-core library from osparc-simcore
- https://github.com/ITISFoundation/osparc-simcore/issues/3638
- https://github.com/ITISFoundation/osparc-simcore/issues/3421
- https://github.com/ITISFoundation/osparc-issues/issues/638
- https://github.com/ITISFoundation/osparc-simcore/issues/2410
- https://github.com/ITISFoundation/osparc-simcore/issues/3541
- https://github.com/ITISFoundation/osparc-simcore/issues/3387

**Comment by sanderegg** [comment]
## Update on sprint [Zefram Cochrane](https://github.dev/ITISFoundation/osparc-issues/blob/master/reviews/20230111_ZeframCochrane.md)
### User support

### Security
### Bugfixes / Technical debt
### CI/CD
### e2e testing
### Pre/releases during this sprint
### Dependencies
### DevOps

**Comment by sanderegg** [comment]
## Update on sprint [Resistance is Futile](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230220_ResistanceIsFutile.md)
### User support
### Security
### Bugfixes / Technical debt
- https://github.com/ITISFoundation/osparc-simcore/pull/3886
- https://github.com/ITISFoundation/osparc-simcore/pull/3879
- https://github.com/ITISFoundation/osparc-simcore/pull/3871
- https://github.com/ITISFoundation/osparc-simcore/pull/3874
- https://github.com/ITISFoundation/osparc-simcore/pull/3868
- https://github.com/ITISFoundation/osparc-simcore/pull/3843
- https://github.com/ITISFoundation/osparc-simcore/pull/3873
- https://github.com/ITISFoundation/osparc-simcore/pull/3872
- https://github.com/ITISFoundation/osparc-simcore/pull/3870
- https://github.com/ITISFoundation/osparc-simcore/pull/3861
- https://github.com/ITISFoundation/osparc-simcore/pull/3850
- https://github.com/ITISFoundation/osparc-simcore/pull/3845
- https://github.com/ITISFoundation/osparc-simcore/pull/3846
- https://github.com/ITISFoundation/osparc-simcore/pull/3835
- https://github.com/ITISFoundation/osparc-simcore/pull/3693
- https://github.com/ITISFoundation/osparc-simcore/pull/3839
- https://github.com/ITISFoundation/osparc-simcore/pull/3826
- https://github.com/ITISFoundation/osparc-simcore/pull/3828
- https://github.com/ITISFoundation/osparc-simcore/pull/3757
- https://github.com/ITISFoundation/osparc-simcore/pull/3761

### CI/CD
- https://github.com/ITISFoundation/osparc-simcore/pull/3751
### e2e testing
### Pre/releases during this sprint
- https://github.com/ITISFoundation/osparc-issues/issues/867
- https://github.com/ITISFoundation/osparc-issues/issues/865
- https://github.com/ITISFoundation/osparc-issues/issues/861
- https://github.com/ITISFoundation/osparc-issues/issues/857
### Dependencies
### DevOps

**Comment by sanderegg** [comment]
## Goal for sprint [Mithril](https://github.com/ITISFoundation/osparc-issues/milestone/40)
- TBD

**Comment by mrnicegyu11** [comment]
## Goal for sprint [Mithril](https://github.com/ITISFoundation/osparc-issues/milestone/40)
#### Taken from https://git.speag.com/oSparc/osparc-ops-environments/-/issues?milestone_title=Mithril


- [PoC: connect a computer using separate ITIS account to osparc.io](https://git.speag.com/oSparc/osparc-ops-environments/-/issues/493) 
- [Increase necessary limits for AppTeam Std Simulations on S4L/AWS](https://git.speag.com/oSparc/osparc-ops-environments/-/issues/492)
#492 · created 2 minutes ago by [Dustin Kaiser](https://git.speag.com/kaiser)  [ Mithril ](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?milestone_title=Mithril) 
[High Priority](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?label_name%5B%5D=High+Priority)
- [Find a way to know how many instances for a given type of instance is available on a subnet in aws](https://git.speag.com/oSparc/osparc-ops-environments/-/issues/487)
#487 · created 2 days ago by [Alexandre Allexandre](https://git.speag.com/allexandre)  [ Mithril ](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?milestone_title=Mithril) 
[High Priority](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?label_name%5B%5D=High+Priority)
- [s4l-lite monitoring dashboard](https://git.speag.com/oSparc/osparc-ops-environments/-/issues/491)
#491 · created 2 days ago by [Dustin Kaiser](https://git.speag.com/kaiser)   Mithril
- [Not able to connect to AWS monitoring](https://git.speag.com/oSparc/osparc-ops-environments/-/issues/490)
#490 · created 2 days ago by [Matus Drobuliak](https://git.speag.com/drobuliak)  [ Mithril ](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?milestone_title=Mithril) 
[Question](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?label_name%5B%5D=Question)
- [Set SIMCORE_VCS_RELEASE_TAG and SIMCORE_VCS_RELEASE_DATE in agent_create_stack_script](https://git.speag.com/oSparc/osparc-ops-environments/-/issues/484)
#484 · created 3 days ago by [Pedro Crespo-Valero](https://git.speag.com/crespo)   Mithril
- [Rational about making aws prod more redudant and stable](https://git.speag.com/oSparc/osparc-ops-environments/-/issues/488)
#488 · created 2 days ago by [Alexandre Allexandre](https://git.speag.com/allexandre)   Mithril
- [Create a test to check that the maintenance-page for TIP is up](https://git.speag.com/oSparc/osparc-ops-environments/-/issues/358)
#358 · created 3 months ago by [Alexandre Allexandre](https://git.speag.com/allexandre)  [ Mithril ](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?milestone_title=Mithril) 
[High Priority](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?label_name%5B%5D=High+Priority)
- [upgrade graylog to version 5?](https://git.speag.com/oSparc/osparc-ops-environments/-/issues/420)
#420 · created 1 month ago by [Sylvain Anderegg](https://git.speag.com/anderegg)  [ Mithril ](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?milestone_title=Mithril) 
[Low priority](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?label_name%5B%5D=Low+priority)
- [upgrade portainer](https://git.speag.com/oSparc/osparc-ops-environments/-/issues/419)
#419 · created 1 month ago by [Sylvain Anderegg](https://git.speag.com/anderegg)  [ Mithril ](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?milestone_title=Mithril) 
[Low priority](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?label_name%5B%5D=Low+priority)
- [Grafana Dashboard Display in the osparc office](https://git.speag.com/oSparc/osparc-ops-environments/-/issues/441)
#441 · created 2 weeks ago by [Dustin Kaiser](https://git.speag.com/kaiser)  [ Mithril ](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?milestone_title=Mithril) 
[paused / blocked](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?label_name%5B%5D=paused+%2F+blocked)
- [Mail Server - test aws solution](https://git.speag.com/oSparc/osparc-ops-environments/-/issues/432)
#432 · created 3 weeks ago by [Alexandre Allexandre](https://git.speag.com/allexandre)  [ Mithril ](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?milestone_title=Mithril) 
[CURRENTLY_DOING](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?label_name%5B%5D=CURRENTLY_DOING)
[High Priority](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?label_name%5B%5D=High+Priority)
- [Set latest Autoscaling service ENVs](https://git.speag.com/oSparc/osparc-ops-environments/-/issues/479)
#479 · created 4 days ago by [Sylvain Anderegg](https://git.speag.com/anderegg)  [ Mithril ](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?milestone_title=Mithril) 
[During maintenance](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?label_name%5B%5D=During+maintenance)
- [Credentials to access AWS costs](https://git.speag.com/oSparc/osparc-ops-environments/-/issues/468)
#468 · created 1 week ago by [Elisabetta Iavarone](https://git.speag.com/iavarone)   Mithril
- [Create admin user in all deploys](https://git.speag.com/oSparc/osparc-ops-environments/-/issues/426)
#426 · created 3 weeks ago by [Pedro Crespo-Valero](https://git.speag.com/crespo)  [ Mithril ](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?milestone_title=Mithril) 
[High Priority](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?label_name%5B%5D=High+Priority)
[paused / blocked](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?label_name%5B%5D=paused+%2F+blocked)
- [Deployment agent: Massive Refactoring, bugFix, Tag Sync](https://git.speag.com/oSparc/osparc-ops-environments/-/issues/452)
#452 · created 2 weeks ago by [Dustin Kaiser](https://git.speag.com/kaiser)  [ Mithril ](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?milestone_title=Mithril) 
[CURRENTLY_DOING](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?label_name%5B%5D=CURRENTLY_DOING)
[High Priority](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?label_name%5B%5D=High+Priority)
- [REGISTRY_SSL is hard-coded and does not fetch its value from the configuration for staging-aws](https://git.speag.com/oSparc/osparc-ops-environments/-/issues/480)
#480 · created 4 days ago by [Sylvain Anderegg](https://git.speag.com/anderegg)  [ Mithril ](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?milestone_title=Mithril) 
[During maintenance](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?label_name%5B%5D=During+maintenance)
- [branch used for staging AWS is not the latest name of the staging branch](https://git.speag.com/oSparc/osparc-ops-environments/-/issues/481)
#481 · created 4 days ago by [Sylvain Anderegg](https://git.speag.com/anderegg)  [ Mithril ](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?milestone_title=Mithril) 
[Discussion](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?label_name%5B%5D=Discussion)
- [Add graylog alert for IP range exhaustion](https://git.speag.com/oSparc/osparc-ops-environments/-/issues/477)
#477 · created 4 days ago by [Dustin Kaiser](https://git.speag.com/kaiser)  [ Mithril ](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?milestone_title=Mithril) 
[High Priority](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?label_name%5B%5D=High+Priority)
[fast](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?label_name%5B%5D=fast)
- [Compile S3 egress costs](https://git.speag.com/oSparc/osparc-ops-environments/-/issues/332)
#332 · created 4 months ago by [Dustin Kaiser](https://git.speag.com/kaiser)  [ Mithril ](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?milestone_title=Mithril) 
[High Priority](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?label_name%5B%5D=High+Priority)
[fast](https://git.speag.com/oSparc/osparc-ops-environments/-/issues?label_name%5B%5D=fast)
- [Update PULL_REQUEST_TEMPLATE message to improve communication with devops](https://git.speag.com/oSparc/osparc-ops-environments/-/issues/486)
#486 · created 2 days ago by [Pedro Crespo-Valero](https://git.speag.com/crespo)   Mithril

**Comment by pcrespov** [comment]
## Goal for sprint [Jelly Beans](https://github.com/ITISFoundation/osparc-issues/milestone/41)
- ...
- ...

**Comment by pcrespov** [comment]
## Goal for sprint [Pastel de Nata](https://github.com/ITISFoundation/osparc-issues/milestone/45)

- Details in https://github.com/orgs/ITISFoundation/projects/9/views/34
-

**Comment by pcrespov** [comment]
## Update for sprint [Pastel de Nata](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230602_PastelDeNata.md)
- releases
- mypy
- flaky
- SEE https://github.com/orgs/ITISFoundation/projects/9/views/34

**Comment by pcrespov** [comment]
## Update [Watermelon](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230707_Watermelon.md)

- [maintenance view](https://github.com/orgs/ITISFoundation/projects/9/views/34)
   -  Code quality assessment: 
       - Finished with `mypy` (type-checking)
       - Integrated [ruff](https://beta.ruff.rs/docs/): an extremly fast python linter
   - 
- [devops view](https://github.com/orgs/ITISFoundation/projects/9/views/38)

**Comment by mrnicegyu11** [comment]
## Update for sprint [Watermelon](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230707_Watermelon.md)
- releases
- upgrades dependencies
- DevOps items see https://github.com/orgs/ITISFoundation/projects/9/views/38

**Comment by sanderegg** [comment]
https://github.com/orgs/ITISFoundation/projects/9/views/31?filterQuery=label%3Abug%2Ct%3Abug%2Ctype%3Abug+milestone%3ASundae

**Comment by sanderegg** [comment]
# Update [Baklava](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230908_Baklava.md)
In details:
- [Maintenance view](# Update [Baklava](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230908_Baklava.md))

**Comment by elisabettai** [comment]
@sanderegg, @pcrespov, @matusdrobuliak66. I am closing this one. For Y7 (simcore)-related maintenance please use this new one #1108 

@mrnicegyu11, @YuryHrytsuk: for operations, we have a new issue in Y7 as well: #1109. I guess we can move the tasks still open here in that new one. I can do that, if that's useful.

@sanderegg, @pcrespov, @matusdrobuliak66, @mrnicegyu11, @YuryHrytsuk. In Y7, we also have a series of new cases, which are a bit of mixture of comp. backend, operations, monitoring, etc... Those should cover the work we're doing  for the release. Those new cases are:
#1100 
#1101 
#1102 
Maybe I will try to link the new ones with the work packages we already have. The goal is not to add more work/useless issues, only making reporting on those new milestones easier. 😉
