### ISSUE TITLE
everybody at z43 uses osparc for python/matlab scripting

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-issues#68]
Niels wants everybody at z43 to use osparc in the context of their scripting. the idea is that this will give us a lot of feedback on usability.
currently, people write their own scripts all the time, but these scripts are rarely archived, shared, described. they can also not readily be applied to crunch large amounts of data due to the restriction of local machines.
the goal is to create an experience in osparc, where people will feel that they benefit from doing that work on osparc.
- [x] in a first step, the team should come up with suggestions, how that experience could be achieved. i suggest starting with python and later shifting to matlab. points to consider will include:
- ease of shifting script to osparc
- ease of editing and rapidly reevaluating existing script in osparc (python notebooks?)
- ease of creating new script (notebook level, IDE level?)
- ease of organizing scripts (people might have many scripts, many variant of the same script, maybe a folder structure)
- ease of sharing scripts (publishing as a service); if there are many, some organization structure might also be needed
- ease of documenting what a script does, how it is used...
- ease of executing a script that requires access to locally stored data (mount drive?)
- ease of applying script to large amounts of data (crunching)

------------------------------------------
according to our discussion from today (May 12th)
- [x] get the DALCO cluster
- [x] s4l python version (already there?)
- [x] sharing studies, services (not just templates) -> sharing not just a copy, but the actual thing (how are conflicts handled? non-concurrence initially)
- [x] organization of scripts/projects (tree? catalog search?...) -> tags
- [ ] usage standard for z43 / guidelines
-------------------------------------------------- (up to here: needed for release to z43?)
- [x] versioning / branching
- [x] matlab / octave
- [ ] launch isolve on osparc-cloud by pressing a button in s4l
- [ ] launch object as blackbox / viewable notebook / interactive notebook / editable code (related to fine-grained access rights issue)
- [x] (bring process to data)

we need to be production level when we release it (in house)

**Comment by esraneufeld** [comment]
sylvain reboux would  be valuable to include in defining and later testing the functionality.

**Comment by pcrespov** [comment]
State:

- Review with SyR and EN on potential features based on z43 activities.
- First use-case defined: a python script runner [expected by mid next week]

**Comment by pcrespov** [comment]
Update Brown Islands sprint:

- Finishing **alpha stage**
- Created and classified a list of possible features useful for Z43
- python-script-runner user case resolved [demo]
- Main features missing (in order of importance):
    - Machines at Z43 (next week)
    - S4L (ongoing: ??)
    - Access to sandbox at Z43 (not started)
    - Export projects (ongoing: 1.5 sprint)
    - Matlab (will be based on python feature). Somebody must look at the license!
    - New sidecars for dynamic services (not started: 2-3 sprints more)

- **Beta stage** expected mid next sprint
- Brownbag presentation to introduce osparc to Z43

**Comment by drniiken** [comment]
[usecases_z43usesOSPARC.pdf](https://github.com/ITISFoundation/osparc-issues/files/4198757/usecases_z43usesOSPARC.pdf)

**Comment by drniiken** [comment]
According to our meeting on 20200211, more details are provided within the use cases (see attached pdf).

**Comment by pcrespov** [comment]
## Update [Dim Sum](https://github.com/ITISFoundation/osparc-simcore/milestone/22) for [review](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20200406_DimSum.md)

- isolve as computational services: drag&drop input file, connect solver, run, download; minimal licensing solution (WIP)
- jupyterlab with different kernels (WIP: integration missing)
    - python
    - rec5g (customized to Z43's python library)
    - octave
    - matlab
- UI: one-click to jupyterlab

**Comment by esraneufeld** [comment]
regarding the high priority items above:
- _get the DALCO cluster_
should be clear
- _s4l python Jupyter version_
close to ready
- _sharing studies, services (not just templates)_
still needed: 
  - sharing of services (e.g., Jupyter notebook incl. the content of work-folder, without need for sharing the entire study)
  - ability of defining who has access to my study/service, without being a (super)admin (e.g., i want to share my script with thomas fussinger / to work with him on that script)
  - finer control on rights (view, execute, edit copy, edit master)
- _organization of scripts/projects (tree? catalog search?...)_ 
  - discussion was started with pedro for long term vision. define steps towards that.
  - xxxxxxxxx
  - see also the Issue #xxx 
- _usage standard for z43 / guidelines_
should not be handled by developers. Katie and EN will organize it.

note: is it a good decision to only save things in the work folder? should we not drop that one and save the entire root folder?

**Comment by pcrespov** [comment]
## Update on [C.Maurer](https://github.com/ITISFoundation/osparc-simcore/milestone/22) sprint for [review](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20200608_Chrigel_Maurer.md)

### Current status

- Focus on **JupyterLab** services with math kernels in python and octave
- BBL talk: Introduction of osparc to Z43 . **The slides are available [here]:(https://docs.google.com/presentation/d/1rcwr6BxPXAw6ksMKpgkOPTnndnrv743ru6d_zEz1Wgs/edit?usp=sharing)**. A demo covered the following points:
  - Dashboard
      - Cards: author, organization, description, ...
      - Tagging and filtering cards
  - Scripting Development Environment: jupyterlab customized for Z43
      - File explorer: with input, output, work dirs 
      - Notebooks: half-code & half-document
      - Kernels: octave (matlab-like), python (+maths, +sim4life, … )
      - Integrated version control
      - Many more extras: interactive plots, slides, editor, markdown, ...
  - Studies: connecting your “program” to other “programs” via inputs/outputs
  - Share with everyone you like: export, collaborate, and publish (e.g. NIH-SPARC Portal website published simulations)
  - Integrated doc, feedback/issues 

### Ongoing development + Next steps

- Release to staging of first version of JupyterLab math (fix pending)
- Create customized JupyterLab with sim4life kernel in python
- Creation of a services catalog such that all services, as studies, can be also shared/classified/discovered etc

**Comment by pcrespov** [comment]
## Update on [Huo Guo](https://github.com/ITISFoundation/osparc-simcore/milestone/25) sprint for [review](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20200706_HuoGuo.md)

### Current status

- ``jupyterlab``: Released to staging of first version of JupyterLab math and [**new** version](https://git.speag.com/oSparc/sparc-internal/-/blob/master/services/jupyter-octave-python-math/CHANGELOG.md) in master. 
- ``s4l python version``:  Implemented customized JupyterLab with sim4life kernel in python (almost done) 
- Created classifiers repo (including CI/CD). Ready to use in https://git.speag.com/oSparc/explore
- ``sharing studies`` (ongoing) with groups, lock mechanism.

### Ongoing development + Next steps

- Finish customized JupyterLab with sim4life kernel in python
- Creation of a services catalog such that all services, as studies, can be also shared/classified/discovered etc
