### ISSUE TITLE
M7 Create (Model) Service Section on the Portal

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#683]
Section on the Portal that displays services available on o²S²PARC (criterion for appearing in that list remains to be defined). A context menu action allows instantiating a new study featuring that service.

Deliverable: Section on the Portal that displays and provides access to o²S²PARC services
Deadline: Month 7

[Wrike M2.2](https://www.wrike.com/workspace.htm?acc=3203588#/task-view?id=916247517&pid=916190536&cid=720993193)

```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4223
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/945
- [x] CCB feedback has been address by @ignapas on May 22 and [PR171](https://github.com/nih-sparc/sparc-api/pull/171) and [PR 657](https://github.com/nih-sparc/sparc-app/pull/675) have been merged. See [wrike](https://www.wrike.com/open.htm?id=1073800205)
- [x] Documentation for the Portal (docs.sparc.science) @elisabettai
```

**Comment by pcrespov** [comment]
## Goal for sprint [Mithril](https://github.com/ITISFoundation/osparc-issues/milestone/40)
-

**Comment by ignapas** [comment]
![Screenshot from 2023-03-22 15-34-31](https://user-images.githubusercontent.com/4764217/226959823-d4190e41-52af-484f-8542-322fd1c07d56.png)

Those are the requirements as described bue Sue Tappan in the [wrike ticket](https://www.wrike.com/open.htm?id=1073800205). Unauthorized users need to land in the login page with a message saying that the current service requires authentication. After a successful login, the user needs to end in the new study with the requested service as the only node. For this:
* The backend redirects the ``/view`` request to the login page (``/?redirectUrl=/view?viewer_key=simcore/services/dynamic/sim4life&version=102``) with the query parameter ``redirectUrl`` that contains the URL that needed authentication (needs to be URL encoded -  '%2Fview%3Fviewer_key%3Dsimcore%2Fservices%2Fdynamic%2Fsim4life%26version%3D102') @pcrespov ?
* After successful login, the front-end jumps to the ``redirectUrl`` and everything works @odeimaiz ?

**Comment by pcrespov** [comment]
@ignapas @odeimaiz  I think we already have all the mechanisms in place (front-end & backend) to implement the workflow in the for auth or non-auth users. We might have to polish messages. In any case, let's review that together after lunch.

**Comment by pcrespov** [comment]
## Update for sprint [Mithril](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230324_Mithril.md)

- Completed with a different design variation
- See PR references above for details
- @ignapas has a movie that demo the GUI of this issue

**Comment by sanderegg** [comment]
- [ ] release to production
- [ ] gif animations for information to the other cores

**Comment by mguidon** [comment]
Feedback from CCB meeting (from Dominic, UI/UX)


![Image](https://user-images.githubusercontent.com/33161876/230208063-b6c4d635-46f1-4710-8847-43e0af871dee.png)


The button must be secondary one, not a primary one.

**Comment by pcrespov** [comment]
- Created https://github.com/ITISFoundation/osparc-simcore/issues/4082 with these changes so it could get to production asap

**Comment by pcrespov** [comment]
## Update for sprint [Jelly Beans](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230428_Jelly_Beans.md)
- osparc side in production from ITISFoundation/osparc-simcore#4082
- At this point, only available in https://staging.sparc.science/resources/osparc-services

**Comment by pcrespov** [comment]
## Goal for sprint [Pastel de Nata](https://github.com/ITISFoundation/osparc-issues/milestone/45)
- ...

**Comment by mguidon** [comment]
There is more from the CCB side. @ignapas This should be addressed within the QA Period

https://www.wrike.com/open.htm?id=1073800205

**Comment by elisabettai** [comment]
## Update [Watermelon](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230707_Watermelon.md)
**Status**: completed. oSPARC public services are available on the SPARC Portal (in production), under Tool & Resources at: https://sparc.science/resources/osparc-services. In addition, deprecated and retired services are not listed anymore.
