### ISSUE TITLE
M12 API tutorial

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#710]
Create a tutorial that illustrates how to use the newly created o²S²PARC API functionality as part of the overall DRC API.

Deliverable: The above described o²S²PARC / DRC API (and Python client) functionality

[Wrike M4.2](https://www.wrike.com/open.htm?id=935194598)
```[tasklist]
### Tasks
- [ ] Review scripts osparc-simcore/test/public-api/examples and convert to tutorials
- [ ] https://github.com/ITISFoundation/osparc-simcore-clients/issues/71
```

```[tasklist]
### Baklava
- [ ] https://github.com/ITISFoundation/osparc-simcore-clients/issues/48
```

```[tasklist]
### Sundae
- [ ] https://github.com/ITISFoundation/osparc-simcore-clients/issues/48
```

```[tasklist]
### Watermelon
```

**Comment by bisgaard-itis** [comment]
# Update [Watermelon](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230707_Watermelon.md)
- Added functionality in sparc.client for basic tutorial
- Plan for adding more tutorials

**Comment by elisabettai** [comment]
@pcrespov, would you know the outcome of sprint Watermelon? I guess @bisgaard-itis has added the e2e test (second point on your last comment).

**Comment by pcrespov** [comment]
> 

@elisabettai  there is indeed an e2e test. SEE [here](https://git.speag.com/oSparc/e2e-portal-testing/-/blob/master/.gitlab-ci.yml#L91-188). Unfortunately my comment in Jun22 was not added as task so probably @bisgaard-itis missed to check that. Pease update the issue tasks when @bisgaard-itis is back. thx

**Comment by elisabettai** [comment]
## Update Watermelon
- Added e2e For e that makes sure it runs against a matrix of deployed apis, see [here](https://git.speag.com/oSparc/e2e-portal-testing/-/blob/master/.gitlab-ci.yml#L91-188)


@bisgaard-itis please update the outcome of last sprint (Watermelon). Please also check that the tasks we added for the current sprint (Sundae) sound reasonable.

**Comment by bisgaard-itis** [comment]
@elisabettai there is only a single entry in https://github.com/ITISFoundation/osparc-simcore-clients/issues/48 which has not yet been completed (turning your user-story into code for demonstrating cross-functionality between the different cores). Would it be OK for you if I create a separate ticket for that one? Apart from that one it seems to me all entries for Watermelon and Baklava are achieved, do you agree?

**Comment by elisabettai** [comment]
This is done since we have:
- A [Jupyter notebook tutorial](https://github.com/nih-sparc/sparc.client/blob/main/docs/tutorial-osparc.ipynb) on the SPARC Client repo
- The same tutorial has been added as markdown to the [SPARC Doc website](https://docs.sparc.science/docs/sparc-python-client). 

I'm closing this and moved the remaining tasks to a tmp list in https://github.com/ITISFoundation/osparc-issues/issues/952

**Comment by elisabettai** [comment]
Now we have also a new issue for the cross-core tutorial (#1088). The deadline has not been defined yet, I put temporarily Nov 30 (end of Q1).

**Comment by bisgaard-itis** [comment]
> Now we have also a new issue for the cross-core tutorial (#1088). The deadline has not been defined yet, I put temporarily Nov 30 (end of Q1). fyi @bisgaard-itis

Perfect! Thanks a lot
