### ISSUE TITLE
M4 Launch Computational Study Parameters from Portal

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-issues#711]
- Extend existing APIs (computational API, study creation and access, platform API), add new APIs (progress API, import/export API) as required by users and in support of the DRC APIs
- exposing launching of computational study with given input parameters / data; initially focusing on similar use-cases as the Portal-launched simulations

Deadline: Month 4

[Wrike M4.1.3](https://www.wrike.com/open.htm?id=921191412)

```[tasklist]
### Tasks
- [x] get solver i/o schemas
- [x] set solver i/o data
- [x] ITISFoundation/osparc-simcore#3940
- [x] get solver job log
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4250
``` 
```[tasklist]
### Sundae
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4177
```

```[tasklist]
### Watermelon

```

**Comment by pcrespov** [comment]
## Goal for sprint [Mithril](https://github.com/ITISFoundation/osparc-issues/milestone/40)
-

**Comment by pcrespov** [comment]
## Update for sprint [Mithril](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230324_Mithril.md)

- ITISFoundation/osparc-simcore#3940
-

**Comment by pcrespov** [comment]
## Goal for sprint [Jelly Beans](https://github.com/ITISFoundation/osparc-issues/milestone/41)

- computational services 
   - [x] get i/o schemas
   - [x] set i/o data
   - [x] run (w/ cluster option)
   - [x] get run log
- studies w/ computational services
   - [x] get i/o schemas
   - [ ] set i/o data
   - [ ] run (w/ cluster option)
   - [ ] get run log (gather all logs)
- ITISFoundation/osparc-simcore#3626
- Report progress in 
- **demo** script?

**Comment by pcrespov** [comment]
## Update for sprint [Jelly Beans](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230428_Jelly_Beans.md)

### api-server 
 - ITISFoundation/osparc-simcore#3626 mostly resolved
 - https://github.com/ITISFoundation/osparc-simcore/issues/4177 in progress
 - https://github.com/ITISFoundation/osparc-simcore/issues/4111 (no progress)
 - https://github.com/ITISFoundation/osparc-simcore/issues/4110 (no progress)

### osparc python client & nih client (no progress)
- Update client 
  -  @elisabettai update doc and extend/new tutorial?
- Report progress to MAP-core
- Integrate with  https://github.com/pcrespov/sparc.client

**Comment by pcrespov** [comment]
## Update for sprint [Pastel de Nata](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230602_PastelDeNata.md)
- Defined [openapi specs](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/ITISFoundation/osparc-simcore/b95953661d79408f2ef88b100ed2b2a9ed3b7b97/services/api-server/openapi-dev.json) for new API release: 
      - https://github.com/ITISFoundation/osparc-simcore/pull/4250

**Comment by elisabettai** [comment]
@pcrespov, this is technically closed for NIH. See update in Wrike [Wrike M4.1.3](https://www.wrike.com/open.htm?id=921191412) for Y6Q2. 
I understand you're using this to track progress on the API side, but maybe we can close this one and use https://github.com/ITISFoundation/osparc-issues/issues/668 from now on.

**Comment by elisabettai** [comment]
@pcrespov, I close this one since the associated milestone for NIH has been approved.

I see that you added a task here for sprint Sundae, which is also part of [sim4life.io - WP6: API](https://github.com/ITISFoundation/osparc-simcore/issues/4177). So we won't lose any information for the current and future sprints is we close this, I hope.
