### ISSUE TITLE
Project Folders in User Workspace (Nov.)

### ISSUE THREAD

**Issue by AntoninoMarioC** [ITISFoundation/osparc-issues#716]
**Wrike Milestone Ticket**

[Y8–MS 1.2.1: Folders in the Dashboard](https://www.wrike.com/open.htm?id=1396934849)

**Describe the user role**
At the moment, users that do not properly define sharing options fill other users's pages with their studies. I do not like to have a mess on my study page, therefore, at least, I'd like to have a separation between my own studies, studies specifically shared with me, and external studies. As well, I'd like to organize my studies according to my own work: CR projects, tests, etc.  It would be also great if the user could also decide to hide some projects, for any reasons. 

**Describe the goal**
A bit of organization in the mess

**Describe the benefit**
Improved mental health and cleaner work organization

More info from https://github.com/ITISFoundation/osparc-issues/issues/977
- a folder can be shared
- every project placed inside a shared folder is automatically "shared"

**Easy UI improvements**
From meeting with users on May 3rd, https://github.com/ITISFoundation/osparc-issues/issues/1403

```[tasklist]
### Event Horizon
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/6871
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1724
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1783
```

```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1613
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1725
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1740
```

```[tasklist]
### MartinKippenbeger
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1723
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/6405
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/6404
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/6386
```

```[tasklist]
### Tom Bombadil
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1556
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1547
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1566
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1567
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/6072
```

```[tasklist]
### Eisbock
- [x] https://github.com/ITISFoundation/osparc-issues/issues/1606
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1568
```

**Comment by pcrespov** [comment]
## Goal for sprint [Jelly Beans](https://github.com/ITISFoundation/osparc-issues/milestone/41)


- review google-drive approach and API regarding folders
- start w/ only folders that contain studies (but cannot be shared)
-

**Comment by matusdrobuliak66** [comment]
<table>
<tr><th>Folder table </th><th>Project to Folder table</th></tr>
<tr><td>

| id | title | parent folder | gid |
| ------ | ------ | ------ | ------ |
| 1 | "User A home" | NULL | A |
| 2 | "User B home" | NULL | B |
| 3 | Folder 1 | 1 | A |
| 4 | Folder 2 | 1 | A |
| 5 | Folder 3 | 4 | A |
| 6 | Folder 4 | 2 | B |

</td><td>

| project id | parent folder | gid | 
| ------ | ------ | ------ |
| Z | 3 | A |
| W | 3 | A |
| H | 5 | A |
| X | 1 | A |
| Y | 1 | A |
| J | 6 | B |
| K | 2 | B |

</td></tr> </table>

### Share study Z with primary group B (user B)

<table>
<tr><th>Folder table </th><th>Project to Folder table</th></tr>
<tr><td>

| id | title | parent folder | gid |
| ------ | ------ | ------ | ------ |

</td><td>

| project id | parent folder | gid | 
| ------ | ------ | ------ |
| Z | 2 | B |

</td></tr> </table>

### Share study H with standard group D (where user B belongs)

<table>
<tr><th>Folder table </th><th>Project to Folder table</th></tr>
<tr><td>

| id | title | parent folder | gid |
| ------ | ------ | ------ | ------ |

</td><td>

| project id | parent folder | gid | 
| ------ | ------ | ------ |
| H| NULL | D |

</td></tr> </table>

### Share folder 1 with primary group B (user B)

<table>
<tr><th>Folder table </th><th>Project to Folder table</th></tr>
<tr><td>

| id | title | parent folder | gid |
| ------ | ------ | ------ | ------ |
| 7 | Folder 1 | 2 | B |

</td><td>

| project id | parent folder | gid | 
| ------ | ------ | ------ |
| Z | 7 | B |
| W | 7 | B |

</td></tr> </table>

### Share folder 3 with standard group D (where user B belongs)

<table>
<tr><th>Folder table </th><th>Project to Folder table</th></tr>
<tr><td>

| id | title | parent folder | gid |
| ------ | ------ | ------ | ------ |
| 7 | Folder 3 | NULL | D |

</td><td>

| project id | parent folder | gid | 
| ------ | ------ | ------ |
| H | 7 | D |

**Comment by pcrespov** [comment]
DUPLICATED https://github.com/ITISFoundation/osparc-issues/issues/977

**Comment by esraneufeld** [comment]
during the realization of the folders on the dashboard, please also consider the related discussions in [this document](https://docs.google.com/document/d/1tZDq71YyXeqbrJMCNJ-ueGOH3FE8FHcKAsdGvcEfr0c/edit?usp=sharing)

namely the part on folders, and also the part on how snapshots (versioning/branching)

**Comment by elisabettai** [comment]
This was also discussed on Jan.17 2024, before sim4life.io release:

**Folders**

Doing this properly including sharing functionality is very tricky. Adding a proper folder structure requires adding new tables in the database to keep track of the metadata. We propose to re-use the current tagging functionality 

The user experience will be similar to the “Tutorials” tab

**Implementation details**:
Add API endpoints to query all available tags and projects therein
Frontend will create virtual folders based on tags

**Open questions**:
It is still unclear how this should look and feel, therefore we will create a proposal

fyi @drniiken, I guess this what you had in mind during PM1 earlier today.

**Comment by cosfor1** [comment]
When a folder contains no folders, can it be shown without a collapsible button next to it, in the folders view which will open when a project is moved to a folder? In this way we can avoid showing a loading icon when the collapsible button is clicked, but there is nothing to be loaded.

Thank you,\
Cosimo

![Image](https://github.com/user-attachments/assets/9c51775f-3618-4a31-876a-04723e039cec)

![Image](https://github.com/user-attachments/assets/1284f8cc-3330-446c-9e71-7a5133aea7c6)

![Image](https://github.com/user-attachments/assets/1b79c678-cfc3-430f-aa67-9e3f13329e9e)

**Comment by mguidon** [comment]
- Moving folders between workspaces: frontend ready, backend not (currently "stay tune")
- Search folder listing: 3 endpoints (+1 for folders +1 for workspace) --> Full search (prjocets is done)
- Drag and drop (frontend only thing)

**Comment by calys** [comment]
Remaining todos:

- Moving folders between workspaces
- Drag and drop (see issue 1783)
- Have a debugging session with Andreas Christ to understand what his issues are and see if they can be fixed
