### ISSUE TITLE
s4l-lite:web features & ui

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-issues#741]
For a comprehensive list of features/issues, please see:

- Task list for s4l:lite in [gitlab](https://git.speag.com/oSparc/osparc-s4l/-/issues?scope=all&state=opened&milestone_title=sim4life%3Aweb%20light&not[label_name][]=Ready%20to%20test)
- Task list for s4l:lite on tab `Feature Completeness` in [googledocs]( https://docs.google.com/spreadsheets/d/1MLVVAa8Vr9or8hxmq5FIV40FGdl7wjM8c69Q6ijksgU/edit?usp=sharing)

**Comment by esraneufeld** [comment]
@colinRawlings @odeimaiz 
please, fill with content in accordance to the discussion with Nik, as well as the existing list for S4L

**Comment by colinRawlings** [comment]
Task list here on tab `Feature Completeness (Nik)` 

or in [gitlab](https://git.speag.com/oSparc/osparc-s4l/-/issues?milestone_title=sim4life%3Aweb+light)

**Comment by mguidon** [comment]
## Goal for sprint [Katherine Switzer](https://github.com/ITISFoundation/osparc-issues/milestone/36)

- [ ] [Smurfy](https://git.speag.com/oSparc/osparc-s4l/-/issues/415)

**Comment by mrnicegyu11** [comment]
## Additional Setup @mguidon 
- [ ] New license server with light (requires env var)

**Comment by mguidon** [comment]
## Update for sprint [Athena] (https://github.com/ITISFoundation/osparc-issues/milestone/36)

### @mguidon
- [ ] [Waveguide Sources](https://git.speag.com/oSparc/osparc-s4l/-/issues/370) (**ongoing: Coax to Waaveguide Tutorial**)
- [ ] Dosimetry
  - [ ] [MBSAR ](https://git.speag.com/oSparc/osparc-s4l/-/issues/395)
  - [ ] [Bi-static RCS](https://git.speag.com/oSparc/osparc-s4l/-/issues/382)
  - [ ] [Dosimetry](https://git.speag.com/oSparc/osparc-s4l/-/issues/377)
     - [ ] IEEE Line Averaged
     - [ ] SurfAvg.PowerDensity
     - [ ] SurfAvg.SAPD
     - [ ] SurfAvg.fSAPD
     - [ ] SurfAvg.MaxExposure
     - [ ] TER

### @elisabettai
- [ ] [Smurfy](https://git.speag.com/oSparc/osparc-s4l/-/issues/415)

### @colinRawlings
- [ ] [Voxel Extended Viewer](https://git.speag.com/oSparc/osparc-s4l/-/issues/412)
- [ ] [User defined Signal](https://git.speag.com/oSparc/osparc-s4l/-/issues/369) 
- [ ] [Voxel Importer](https://git.speag.com/oSparc/osparc-s4l/-/issues/365) 

### @ignapas
- [ ] [Expressions](https://git.speag.com/oSparc/osparc-s4l/-/issues/367) @ignapas @odeimaiz @colinRawlings

**Comment by mguidon** [comment]
## Pre-Planning for sprint [Zefram Cochrane](https://github.com/ITISFoundation/osparc-issues/milestone/37)
