### ISSUE TITLE
oSPARC: S4L-Lite

### ISSUE THREAD

**Issue by odeimaiz** [ITISFoundation/osparc-issues#765]
- [x] Landing-page: update company name
- [x] Add Licensing to cookie disclaimer
- [x] Feedback by email and Link to forum
- [x] Studies/Projects Templates/Tutorials organization
- [x] 2FA, improve UX
- [x] Edit study name from Navigation Bar
- [x] Download logs from NavBar
- [x] Dashboard button with home icon
- [x] Information button in Navigation Bar with study-service merged info
- [x] Quick start guide
- [x] Advanced e2e for s4l-lite
- [x] Create Account button: Pops up link to Z43 registration form
- [x] Version Number in service information popup should be displayed more prominent
- [x] Make sharing features more prominent
- [x] Product-specific everyone organization
- [x] Dashboard related documentation in [ZMT github ](https://github.com/zurichmedtech)
- [x] ? References to the osparc software (such as in 'about'): Wording shall be changed.

**Requires backend/devops**
- [x] Refactor product related data @pcrespov
- [x] Move tags ownership to groups @pcrespov 
- [x] Restrict users to open only one study @sanderegg
- [x] https://github.com/ITISFoundation/osparc-issues/issues/777
- [ ] ? New license server: ideally, we use env vars on the platform for this @GitHK @mguidon, see also [this](https://github.com/ITISFoundation/osparc-simcore/issues/3565)
- [x] 2FA @pcrespov
  - [x] Resend code -> https://github.com/ITISFoundation/osparc-simcore/pull/3658
  - [x] Provide an alternative solution -> https://github.com/ITISFoundation/osparc-simcore/pull/3658
  - [x] 2FA env-var needs to go in the Data Base -> https://github.com/ITISFoundation/osparc-simcore/pull/3673
- [x] Include s4l-lite registered users in product-specific everyone organization
- [x] How to generate invitations? https://github.com/ITISFoundation/osparc-simcore/issues/3683 @pcrespov
- [x] Add how to get an invitation link to vendor info in DB. S4L-Lite should point to the zmt website form.  @pcrespov
- [ ] Maintenance: Use the new messaging system to announce scheduled downtimes
  - [x] https://github.com/ITISFoundation/osparc-simcore/pull/3768 @odeimaiz 
  - [ ] itisfoundation/osparc-simcore#1828 @pcrespov @sanderegg
- [x] Timeout after a few idle hours/minutes: S4L state is auto(saved) after X minutes of idling in a temporary file. Then there is 5 Minute warning popup. Then it closes automatically @odeimaiz https://github.com/ITISFoundation/osparc-simcore/pull/3544
- [ ] Service startup: show progress @sanderegg @GitHK (or change the wording) NK says we need to make the startup of s4l-light faster. The progress bar needs to be more verbose and nicer. It should 'flood' the user with more information about the state so it seems like the webpage is "responsive"
- [ ] Make sure invitation (oetikers) is sent email from zmt.swiss
- [ ] For JupyterNotebooks, they currently open in a second tab with the current UUID-based domain-name-based traefik routing approach. We need to audit if this is viable from a security / scalability point-of-view. From a security point of view, maybe start creating auth. token. @GitHK

**Comment by mrnicegyu11** [comment]
## Must-Have
- [x] Trial Accounts are not needed
- [ ] @odeimaiz Talk to Anja and NK about logos and branding
- [ ] Frontend: On landing-page: Remove osparc-simcore mentions and change itisfoundation to ZMT
- [ ] Frontend: Add cookie disclaimer to landing page
- [ ] Frontend: Add a link to S4L Forum page to GUI
- [ ] Timeout without logout or study-closure (discuss this with s4l team) after idling for a few hours
- [ ] Use the new messaging system to announce scheduled downtimes
- [ ] 2FA is set up
- [ ] NK says we need to make the startup of s4l-light faster. The progress bar needs to be more verbose and nicer. It should 'flood' the user with more information about the state so it seems like the webpage is "responsive"
- [ ] Distinguishable pictures (thumbnails) for the tutorials are needed.
- [ ] A "first usage" Tutorial or Movie like in tip.itis.swiss is needed
- [ ] We restrict s4l-web-light-product users to open only one study. This should be handled by the oSparc backend.
- [ ] The Issues/Feedback Button will trigger a email popup to sim4life support (possibly including user_id, project_uuid, ... at our discretion)



## To be discussed / decided
- [ ] NK: "We shall disable accounts after half a year of users not using them" --> What does this mean technically, when is an account considered unused? Will we disable them manually from time to time or have a (semi)automatic procedure?
- [ ] Where should the documentation live? --> The manual will likely live in github... Erdem will talk with @mguidon about this separately
- [ ] Question by EO: Is the 'one-project == one-file' agreed upon? --> It is not yet clear, there are various pros/cons. This needs to be decided
- [ ] For s4l-web-light JupyterNotebooks, they currently open in a second tab with the current UUID-based domain-name-based traefik routing approach. We need to audit if this is viable from a security / scalability point-of-view. A possible blocker could be is s4l-light lives under a `zmt.swiss` subdomain, such as `s4l.zmt.swiss/light`.

## Not fully committed to these features yet:
- [ ] Registration via a zmt.swiss form, possibly automated sign-up link generation via black/white list?

**Comment by mguidon** [comment]
## Pre-Planning for sprint [Zefram Cochrane](https://github.com/ITISFoundation/osparc-issues/milestone/38)

- [ ] Quick start guide
- [ ] 2FA env-var needs to go in the Data Base
- [ ] Service startup: show progress @sanderegg @GitHK (or change the wording) NK says we need to make the startup of s4l-light faster. The progress bar needs to be more verbose and nicer. It should 'flood' the user with more information about the state so it seems like the webpage is "responsive"
- [ ] Maintenance: Use the new messaging system to announce @pcrespov @sanderegg 
- [ ] Timeout after a few hours/minutes --> user logout/close study
- [ ] Define mechanism for invitations and provide them
- [ ] For s4l-web-light JupyterNotebooks, they currently open in a second tab with the current UUID-based domain-name-based traefik routing approach. We need to audit if this is viable from a security / scalability point-of-view. A possible blocker could be is s4l-light lives under a zmt.swiss subdomain, such as s4l.zmt.swiss/light.
