### ISSUE TITLE
TIP v2

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-issues#831]
work on TIP2.0 is starting, for primarily involving melanie and michelle (from auden, coming soon):
- generalization to more than two channels
- accelerated and improved optimization
- variable threshold determination
- more anatomical models, more species (michelle)
- small items from #670 
- (personalization - unlikely to make it in)

```[tasklist]
### Initial Tasks
- [x] Create new version of the services (ES with more species,
- [ ] PP supporting a second voila file), including the new field libraries
- [x] Dashboard: Second plus button that starts the mTI
- [ ] Dashboard: Third plus button that starts the phase modulated TI @odeimaiz
```
```[tasklist]
### Extended Tasklist @melanie_steiner
- [ ] phase modulation
- [ ] finalize visualization of pareto front
- [ ] HF for >2 channels
- [ ] field libraries with additional subjects
- [ ] field libraries with targets
- [ ] field libraries incl reduced resolution variants
- [ ] additional report variants (mTI, phase modulation)
- [ ] minor cleanup & bugfixes & wording & layout
```
```[tasklist]
### Involving the Team (Watermelon)
- [x] support the merging of the new code @mguidon
- [x] make three types of templates available from the dashboard @odeimaiz
- [x] support on voila mode & release (at least twice) @odeimaiz
```
```[tasklist]
### Release Preparations
- [ ] manual update
- [ ] news item & social media
- [ ] video?
```

**Comment by mguidon** [comment]
From our side this requires:

- work on the electrode selector
- merge optimizer and postpro into one service
- come up with a solution for the data
- general support with (s4l-)python

**Comment by mrnicegyu11** [comment]
fyi: unassigned myself since no devops changes seem to be planned for this sprint

**Comment by odeimaiz** [comment]
Mithril:
Enabled the mouse in Electrode Selector (inhouse only)

**Comment by pcrespov** [comment]
## Goal for sprint [Mithril](https://github.com/ITISFoundation/osparc-issues/milestone/40)

- ( @mguidon for the moment I will exclude myself of this issue but do not hesitate to add me back if you require something from me )

**Comment by GitHK** [comment]
There seems to be an issue with the electrode selector used as an upstream service.
- user report https://github.com/ITISFoundation/osparc-issues/issues/943

**Comment by esraneufeld** [comment]
support needed from the team for the forthcoming release"
- creation of new version of the services, including the new field libraries
- modification of the dashboard to allow instantiation of two times of studies: TI and mTI

**Comment by pcrespov** [comment]
## Goal for sprint [Pastel de Nata](https://github.com/ITISFoundation/osparc-issues/milestone/45)
- ...

**Comment by esraneufeld** [comment]
still todo:
- [ ] phase modulation
- [ ] finalize visualization of pareto front
- [ ] HF for >2 channels
- field libraries with 
  - [ ] additional subjects
  - [ ] targets
  - [ ] incl reduced resolution variants
- [ ] additional report variants (mTI, phase modulation)
- [ ] minor cleanup & bugfixes & wording & layout

involves the team:
- [ ] make three types of templates available from the dashboard
- [ ] support the merging of the new code 

release preparations
- [ ] manual update
- [ ] news item & social media
- [ ] video?

**Comment by mguidon** [comment]
# Update [Watermelon](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230707_Watermelon.md)

- [ ] new code synced with latest simphony version
- [ ] removal of optimizer
- [ ] publishing new `ti-postpro` service
- [ ] new templates **ongoing**
