### ISSUE TITLE
TI Planning

### ISSUE THREAD

**Issue by esraneufeld** [ITISFoundation/osparc-issues#91]
Timebox in this SPRINT to 3d

TIsolution will be building dedicated HW to administer temporal interference stimulation and requires associated software for treatment planning (TP).
That TP SW will be built based on oSPARC. 
A first version should be finished by mid 2020. It will primarily require managing of studies, access rights, 3D viewing and picking, visualization, running Python analyses, as well as access to a library of precomputed fields.

For detailed information (e.g., the required steps and functionalities for the first version), see the attached presentation [TI_SW_ideas.pptx](https://github.com/ITISFoundation/osparc-issues/files/3955319/TI_SW_ideas.pptx).

The second version is expected to be an excellent example for the implementation of the guided mode.

all of the below is to be discussed and just a first idea:
------------------------
general considerations:
- [x] precomputed head fields
- [x] accounts, login
- [x] (step-by-step, dedicated view - guided mode)
- [x] navigation: previous / next, ability to jump to any of the completed steps and, continue from there (ask if results should be discarded), return to dashboard (save current state), completing last step returns to dashboard

next steps:
-----------------------------
- [ ] rewrite of optimization service to use joint library with postpro service
- [x] predefined report template (and means for us/users to define that template) that automatically get's evaluated when results are available.
- [x] execution logic, when navigating the bread crumbs / buttons
- [ ] selectable libraries of fields (in setup service) to support different heads, different species, other targets (spinal cord...) 
-> available targets (and later also electrode positions) depend on selection. 
if necessary, this can be a new, first service (e.g., based on issue #8 )
- [x] ( alternative in setup to uniquely select pairs and manually assign currents (rather than optimization) ) <- lower priority

old list of items:
- [ ] dashboard 
new / open (directly jumps to visualization tab, or last completed step) / download previous report
- [ ] select head model (different heads? animal heads? other regions? – NK: start with one head) 
- [ ] select target (parcelation-based) – combine with previous steps, if electrode locations do not change
in tree, visualized in 3D view with highlighting, (un-)picking, multiselection possible
- [ ] select potential electrodes 
3D view picking, with highlighting for current selection, already selected electrodes are coloured in two strong collors (per channel) 
four drop-down selections (two per channel); each with a pick button
- [ ] steering parameters (potentially combined with next step for interactivity, or with previous one)
option enter / optimize
if enter: editable current property per channel
if optimize: optimize when next is pressed / when optimize button is pressed?; show progress while optimization is performed
button to export settings (for transfer to HWSW)
- [ ] visualization
DASH? selection of view (3D, 2D slice, graphs) or pannel?
3D view: quantity selection (modulation amplitude, current per channel, sum of currents), iso-surface of selected quantity, semi-transparent 3D brain w/wo parcelation
slice view: slice orientation (main planes only), quantity selection (modulation amplitude, current per channel, sum of currents), overlaid contours of parcelation?, scroll
2D plots: cumulative histograms (target, non-target), option to add additional curves (selection from parcelation regions), toggle visibility of curves
always displayed scalar quality metrics (focality, coverage), also per parcelation region? safety metrics?
button: download report (pdf?, contains stimulation configuration & settings & all of the above views)

**Comment by mguidon** [comment]
## Status Report after Shu

**Definition of Done**:  Have a workflow with down-sampled simulation results
- electrode selector [100% done]
- optimizer: There is a bug. (Waiting for input from Valeriia, But I strongly suggest I take care of that myself. I just need documentation for the applied algorithm)
- server side functionality for creation of arbitrary dashboards (markdown, screenshots, plots) for report [100 % done]
- automatic loading of optimizer results [75% done]

**Comment by esraneufeld** [comment]
To be done:
- discussion group on UI
- four groups on the setup
- automatic loading of data in last node
- target regions (smash & drop down)
(- production database, mouse database)
- other stuff which is coming

**Comment by esraneufeld** [comment]
next steps
- SR brings the optimizer into shape
- the team creates versions of the optimizer with preloaded fields
- ACa/? writes a voila report service

**Comment by mguidon** [comment]
## Status Report after Rudolph

Work from osparc dev team done (except voila mode for jsmash)

- **electrode selector**: Awaiting Feedback from @esraneufeld regarding grouping of electrodes into pairs
- **optimizer**: Sylvain Reboux is refactoring the kernel. Afterwards reintegration into service can be done
- **postpro**: New voila service strategy applied to jupyter-smash and notebook from Antonino required

**Comment by mguidon** [comment]
## Status Report after Schumann

Work from osparc dev team done (except redeploying services)

- [ ] **Electrode Selector**: As it was 1 year ago. I remember [@Esra Neufeld]() wanted to change the logic of how the groups are created for the pair permutations
- [ ] **Optmizer**: Has been refactored by [@Sylvain Reboux]() but he needs some clarification regarding the N vs N-1 thing in the pre-calculated matrix elements and [@Sylvain Reboux]() and [@Antonino Cassara]() should define the data structure that is going to be passed to the post processing service.
- [ ] **Postprocessing**: Nothing done, requires a notebook from [@Antonino Cassara]()

**Comment by esraneufeld** [comment]
during the forthcoming sprint, a new theme will be applied (in synchrony with bruno)

**Comment by esraneufeld** [comment]
next steps:
- modify electrode placement widget to have four groups, remove option for field library
- refactored sweeper from sylvain; generates table with configurations and performance according to three goals
- voila service that permits to set weight of the three goals, resulting in a sorted table with the 10 prefereable conditions
- after one condition is selected, a corresponding set of visualizations is generated

next iteration
- create variants of electrode placement widget for different species (human, mouse, monkey, rat)
- splitting of visualization service into two: interactive adaptation (fast), report generation (extensive, detailed, accurate)

**Comment by esraneufeld** [comment]
summary of what is missing:
- sweeper service (using common packatge)
- finalization of 3D views (incl. isosurfaces, electrode visualized)
- deployment (in house HW, separated from network)
- minor UX/UI revisions
- manual, movies, news items...
- two factor authentification?
_odei to comple
melanie to complete_

**Comment by elisabettai** [comment]
Closing, follow-up in #670
