### ISSUE TITLE
sim4life.io - WP3: Tracking of resource usage

### ISSUE THREAD

**Issue by drniiken** [ITISFoundation/osparc-issues#922]
## Description

To ensure transparency and accuracy in billing, it is essential to collect and keep track of all resource usage from users, including compute time for simulation hours and S3 storage per user as well as egress costs for download of files. This information must be synchronized with what the customer has paid for, and the data must be stored permanently to accommodate the pay-per-use model.

To make this data accessible to all relevant parties, it will be integrated into multiple systems, including the webpage, product, and API, as well as potentially the finance department for billing.

```[tasklist]
## Tasks
- [x] ~~Potentail Enhancement: Monitor storage costs (e.g. via prometheus S3 exporter ?)~~
- [x] ~~Overload testing (DB,..)~~
- [x] ~~Review Pricing Data Backups @mrnicegyu11 @yuryhrytsuk~~
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1018
- [ ] ITISFoundation/osparc-issues#956
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4674
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1308
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/174
- [x] ~~Setup infrastructure for the second database~~
- [x] ~~Show credits burnt by the running project @odeimaiz @jsaq007~~
- [x] ~~Credits indicator: Bar, Text or Text with Bar to Preferences @odeimaiz~~
```

```[tasklist]
## Schoggilebe
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1133
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1170
- [x] Tagging for cost separation @matusdrobuliak66 @mrnicegyu11
```

```[tasklist]
### ThisIsSparta
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1214
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1242
```

```[tasklist]
### Kobayashi Maru
- [x] Fetching data when I click on the tabs in the billing center
- [x] https://github.com/ITISFoundation/osparc-issues/issues/1213
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1239
```

```[tasklist]
### Microhistory
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4475
- [x] ~~Create Admin/Accountant endpoint for downloading data & modifying prices~~
- [x] Have a script that collects all container seconds per user group for jupyter-smash in AWS prod @mrnicegyu11
- [x] ~~Connect External Service for User Credits~~
- [x] Credits indicator: yellow when it goes below 100$, red bellow 20$ @odeimaiz
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1004
- [x] ~~Inject AWS EC2 instance type to the container labels @sanderegg @matusdrobuliak66~~
- [x] Adding user-selected resoures (cpu/memory) labels to Computational services on start @sanderegg
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4244
- [x] Adding user-selected resoures (cpu/memory) labels to Dynamic services on start  @sanderegg
- [x] ~~Inject project name/node label/user email to the container labels @sanderegg @matusdrobuliak66~~
- [x] Mechanism for handling lost heartbeats @matusdrobuliak66
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4958
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4768
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1131
- [x] get invoices (from the 3rd party payment system) @pcrespov
- [x] Few free welcome credits could be loaded in this private wallet (Show it in dollars, 100$ by default) @pcrespov
- [x] Tier selection, hide it if not Advanced @odeimaiz
```

```[tasklist]
### Quilmes
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1071
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1132
- [x] User's default wallet (on account creation) @pcrepov
- [x] Frontend: Show user credits @odeimaiz
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1142
```

```[tasklist]
### Baklava
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1051
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1007
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1067
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/697
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1070
- [x] Add tracking of iSolve @matusdrobuliak66
- [x] Start to trace additional services @matusdrobuliak66
```

```[tasklist]
### Sundae
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1039
- [x] Frontend: Show wallet info @odeimaiz
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1019
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4523
- [x] Create User Credit History table @matusdrobuliak66
- [x] Create Credit table (mapping of instances, CPU hours to price) @matusdrobuliak66
```

```[tasklist]
### Watermelon
- [ ] ITISFoundation/osparc-issues#955
- [x] https://github.com/ITISFoundation/osparc-simcore/pull/4380 @matusdrobuliak66
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/994
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/995
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4350
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4453
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/3638
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/4322
- [ ] https://github.com/ITISFoundation/osparc-ops-environments/issues/175
```

**Comment by sanderegg** [comment]
## Goal for sprint [Jelly Beans](https://github.com/ITISFoundation/osparc-issues/milestone/41)
- ...
- ...

**Comment by mguidon** [comment]
> 

- Failed jobs will not be billed (we will need to make sure that we disallow starting jobs prior to a downtime). For iSolve it might be possible to estimate the runtime
- We will have two scenarios:
  1. Cloud users will be billed by simulation hours
  2. desktop users that submit simluations will be billed by 100 + X % of our costs (ec2 + egress, egress could be tracked by API)
In general, even if we do not bill it, I would like to know how much S3 storage a user consumes. Also I would like to know how much egress cost the video streaming costs (no on a per user basis). The latter is to get an idea of the cost and whether we should go for a AWS solution for webrtc.

**Comment by pcrespov** [comment]
## Goal for sprint [Pastel de Nata](https://github.com/ITISFoundation/osparc-issues/milestone/45)
- ...

**Comment by sanderegg** [comment]
## Update for sprint [Pastel de Nata](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230602_PastelDeNata.md)
  - new service resource-usage-tracker ready to be used: 
    - https://github.com/ITISFoundation/osparc-simcore/pull/4244
    - https://github.com/ITISFoundation/osparc-simcore/pull/4275

**Comment by matusdrobuliak66** [comment]
## Working comments

**Next steps:**
- adding needed labels to the computational services
- based on @GitHK input: Always check the last updated row -> and start the data fetching/populating of the database from there.
- adding endpoint for frontend (so we can get quick feedback)
- adding useful CLI commands (for example during an outage to be able to run/rerun the concrete task at a specific time)
  - https://github.com/ITISFoundation/osparc-simcore/pull/4380#discussion_r1237479486 
- adding an additional test that will test concurrency (inspired by test_multiple_creation_deletion_of_nodes)
- adding a second data source from the application to get info when computational/dynamic services started/stopped.

**Notes & Discussions:**
- as promql doesn't support pagination when querying, we need to think of a list of regex expressions that would cover containers we would like to monitor (which will fetch a reasonable amount of data) and we will run more background tasks for each item in the list
  - OPEN DISCUSSION (with @mrnicegyu11): should we run all background tasks in one container, or should each background task run as a separate container in our docker swarm. 
- NOTE: potentially introduce a daily aggregated table which will aggregate the data needed for billing service (therefore we would be able to keep the _resource_tracker_container_ table data amount under control.
- NOTE: point of failure
  - resource tracking service is unavailable -> The scheduled task in this service can run even backward, the only important thing is that the Prometheus and its database is available
  - Prometheus outage -> There is a time range where we do not have data because Prometheus was not scraping them -> We will run at least 2 replicas of Prometheus in different nodes
  - There should be another source of data! -> We will store when services were started and stopped from the application.

**Comment by mguidon** [comment]
Next iteration:

- Track instance type
- Have a table in the backend that maps instance type to credits/hour per product
- Provide API for
  - Available Credits left
  - Update of Credit Count after purchase

Do this for comp. service iSolve and sim4life and jupyter-smash

**Comment by matusdrobuliak66** [comment]
IMPLEMENTATION NOTES:


[_5e3d5799c2f3370c861d6889-Implementation Notes - Resource Usage Tracker-200723-065246.pdf](https://github.com/ITISFoundation/osparc-issues/files/12102921/_5e3d5799c2f3370c861d6889-Implementation.Notes.-.Resource.Usage.Tracker-200723-065246.pdf)

original: https://osparc.atlassian.net/wiki/spaces/~5e3d5799c2f3370c861d6889/pages/327681/Implementation+Notes+-+Resource+Usage+Tracker

**Comment by matusdrobuliak66** [comment]
### Goal for Sundae

Next iteration:
- Introduce Wallets
- Have a table in the backend that maps sim4life tier to credits/hour per product
- Provide API for
  - Available Credits left
  - Update of Credit Count after purchase
- Track sim4life tier chosen by user [small, medium, high]


Do this for comp. service iSolve and sim4life and jupyter-smash

**Comment by matusdrobuliak66** [comment]
The connection between director-v2/dynamic services and resource usage tracker:


![Image](https://github.com/ITISFoundation/osparc-issues/assets/60785969/0ab0f3f8-4a24-428a-8c28-e1e6240e33cc)

**Comment by matusdrobuliak66** [comment]
What happens when we hit zero credits?

- sim4life (dynamic service)
  - close the service ("maintenance style")
  - running isolve (computational service)  

- run isolve with the API
  - dumps current state and continue on 
  - kill
  - leave it with some threshold (2% of the existing credits)

- can removed from the wallet (unauthorized)
  - kill

- lose your work

Batch 

Docker freeze container functionality - `docker pause` & `docker unpause`

**Comment by matusdrobuliak66** [comment]
## Update [Baklava](https://github.com/ITISFoundation/osparc-issues/milestone/48)

Done:
 - User center dashboard
 - Collecting and storing events/resources now from all running services (Computational & Dynamic)
 - Created core backend for credit computation/mapping credits to pricing plans
 - Expose top-up credit endpoint to Payment Service

In progress:
- Expose available credit information to the frontend
- Provide wallet_id (where to bill) and pricing_plan_id (what to bill) when starting a service via UI or API.

To do:
- Add a mechanism to close the running status of the service, if the resource tracker will stop recieving heartbeat events
- Stop the running service if there are not enough credits
- Connect simcore to AWS-managed RabbitMQ service
- Connect resource usage tracker to new AWS-managed Postgres database
...

**Comment by matusdrobuliak66** [comment]
## Update [Quilmes / TheNameless](https://github.com/ITISFoundation/osparc-issues/milestone/49)

Done:
 - Showing real credits in the wallet endpoint
 - Sending updates on current available credits in wallets to frontend via websocket
 - Wallet constrained to the specific product (example: osparc, s4l, ...)
 - User default wallet
 - Defining and listing pricing plans

In progress/To do:
- Store in the database the selected pricing plan with the service API
- Extend computation backend to use selected pricing plans 
- Introduce the lost heartbeat mechanism in RUT (to close the transaction if we lose the heartbeat)
- e2e
...

**Comment by matusdrobuliak66** [comment]
# Update [Microhistory]

## Done and working
- 

## should work in 3 weeks
-

## should not be available in 3 weeks
-

**Comment by matusdrobuliak66** [comment]
# Update [ThisIsSparta](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20240202_This_Is_Sparta.md)

## Done
- All known issues with computational backend sending events were fixed and now we are collecting all running jobs correctly. 
- https://github.com/ITISFoundation/osparc-issues/issues/1214
- https://github.com/ITISFoundation/osparc-issues/issues/1242
- https://github.com/ITISFoundation/osparc-simcore/pull/5285 (Burning credits now also works for different products, ex. academia, desktop,...)

## Improvements to be done (not blocking release)
- https://github.com/ITISFoundation/osparc-issues/issues/1133
- "Incremental SUM" of credits (Currently when computing credits on the fly, we are counting the whole history of transactions, in the long term this is unsustainable and we need to compute credits incrementally)
- Continually bill while the transaction is running (Currently we consider the transaction billed only when it is successfully finished)
