### ISSUE TITLE
New version of jupyter-fenics service using .osparc config

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-issues#942]
Open source https://git.speag.com/oSparc/sparc-internal/-/tree/master/services/jupyter-fenics and create a .osparc compatible version of it

```[tasklist]
### Tasks
- [ ] https://github.com/ITISFoundation/cookiecutter-osparc-service/pull/108
- [ ] setup github repo under ITISFoundation and run cookiecutter
- [ ] adapt jupyter base and requirements from original repo
```

**Comment by elisabettai** [comment]
Thanks @pcrespov for this, we also need to do the same for jupyter-chaste: https://git.speag.com/oSparc/services/jupyter-chaste

**Comment by elisabettai** [comment]
Hi @pcrespov, I have some time now to update some of those services to dy-sidecar versions, I'll start with jupyter-chaste.
My plan would be to start from the many examples we have for jupyters (e.g. [jupyter-math](https://github.com/ITISFoundation/jupyter-math)).

Should I also try to extend the existing cookiecutter for jupyterlab-like services? The jupyterlab layout looks a bit different to me compared to https://github.com/ITISFoundation/IEC62209-service/tree/main

**Comment by pcrespov** [comment]
@elisabettai let's catch up on thisone when you are back. thx
