### ISSUE TITLE
sim4life.io - WP5: Dynamic services backend

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-issues#951]
## Description

Interactive services that require real-time user interaction are powered by the dynamic sidecar. Ensuring that the sidecar is both stable and efficient is paramount to providing a good user experience. With that in mind, we have devoted considerable resources to refining and optimizing the design of the sidecar, and we will continue to do so as we roll out new features and capabilities.

Handling large files is another area where we have placed a strong focus. The sidecar is designed to efficiently manage the transfer of large files, ensuring that users can work with data sets in the 100s of GBs with ease.

We will also extend the sidecar API to include features such as the injection of environment variables and files, providing greater flexibility and customizability to our users. Additionally, users will be able to select the hardware on which the sidecar runs directly from the dashboard, ensuring they have the resources they need to get the job done.

```[tasklist]
## Tasks
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4909
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4464
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4468
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4524
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/638
- [ ] ITISFoundation/osparc-issues#618
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4960
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5453
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1222
```

```[tasklist]
### Schoggilebe
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5100
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1175
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1263
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1264
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1262
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5395
```

```[tasklist]
### This is Sparta!
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5250
```

```[tasklist]
### Kobayahsi Maru
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1221
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1055
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/5205
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/5071
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/5189
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/5196
- [ ] https://github.com/ITISFoundation/osparc-simcore/pull/5197
```

```[tasklist]
### Microshistory
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/954
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/3565
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4958
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/3531
```

```[tasklist]
### Quilmes
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1059
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1060
```
```[tasklist]
### Baklava
```
```[tasklist]
### Sundae
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/4351
```
```[tasklist]
### Watermelon
- [ ] https://github.com/ITISFoundation/osparc-simcore/issues/3033
```
```[tasklist]
### Pastel de Nata
- [x] https://github.com/ITISFoundation/osparc-simcore/pull/3812
```

**Comment by GitHK** [comment]
## Update on sprint [Pastel de Nata](https://github.com/ITISFoundation/osparc-issues/milestone/45)

Done:
- https://github.com/ITISFoundation/osparc-simcore/pull/3812

**Comment by mguidon** [comment]
# Update [Watermelon](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230707_Watermelon.md)

**Comment by GitHK** [comment]
# Update [Sundae](https://github.com/ITISFoundation/osparc-issues/blob/master/reviews/20230814_Sundae.md)
Done:
- https://github.com/ITISFoundation/osparc-simcore/issues/3033
- https://github.com/ITISFoundation/osparc-simcore/issues/4351
- https://github.com/ITISFoundation/osparc-simcore/issues/4351

**Comment by GitHK** [comment]
# Update [Microhistory]

## Done and working
- replace osparc identifiers inside compose spec
- user preferences for `fronted` and `user services` are driven by the backend
- autoscaling based on selected machines (I think this should be considered done, MaG ask SAN)

## should work in 3 weeks
- API keys need to be provided created and removed each time a service si started and closed
- upon reaching 0 credits services (computational and dynamic) are killed. Only part missing here is pushing the status of the dynamic services via the backend and no longer polled by the frontend


## should not be available in 3 weeks
- all known bugs that are pending since long ago
