### ISSUE TITLE
User based system wide service preferences

### ISSUE THREAD

**Issue by mguidon** [ITISFoundation/osparc-issues#954]
Some applications have user preferences. We should store them as a file somewhere in S3 ,inject them via dynamic sidecar into the user services and store them back when the applications stops. Destination inside the container could be defined docker image label.

```[tasklist]
### Tasks
- [x] base functionality and backedn integration exposed to the stack
- [ ] https://github.com/ITISFoundation/osparc-issues/issues/1062
- [x] user services integration
```

**Comment by GitHK** [comment]
save in the "database" somewhere a file with the settings. Bypasses S3

**Comment by GitHK** [comment]
@mguidon can I close this case? Have you managed to save the preferences inside the service as well?

**Comment by mguidon** [comment]
We can close it. I think the problem is on my side. If not I will open another issue.
